// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type SchemaValidationOperationSettingsInitParameters struct {

	// (String) When set, this applies a mitigation action to this operation
	// When set, this applies a mitigation action to this operation
	//
	// - `"log"` - log request when request does not conform to schema for this operation
	// - `"block"` - deny access to the site when request does not conform to schema for this operation
	// - `"none"` - will skip mitigation for this operation
	// - `null` - clears any mitigation action
	// Available values: "log", "block", "none".
	MitigationAction *string `json:"mitigationAction,omitempty" tf:"mitigation_action,omitempty"`

	// (String) UUID.
	// UUID.
	OperationID *string `json:"operationId,omitempty" tf:"operation_id,omitempty"`

	// (String) Identifier.
	// Identifier.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-cloudflare/apis/cluster/zone/v1alpha1.Zone
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`

	// Reference to a Zone in zone to populate zoneId.
	// +kubebuilder:validation:Optional
	ZoneIDRef *v1.Reference `json:"zoneIdRef,omitempty" tf:"-"`

	// Selector for a Zone in zone to populate zoneId.
	// +kubebuilder:validation:Optional
	ZoneIDSelector *v1.Selector `json:"zoneIdSelector,omitempty" tf:"-"`
}

type SchemaValidationOperationSettingsObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) When set, this applies a mitigation action to this operation
	// When set, this applies a mitigation action to this operation
	//
	// - `"log"` - log request when request does not conform to schema for this operation
	// - `"block"` - deny access to the site when request does not conform to schema for this operation
	// - `"none"` - will skip mitigation for this operation
	// - `null` - clears any mitigation action
	// Available values: "log", "block", "none".
	MitigationAction *string `json:"mitigationAction,omitempty" tf:"mitigation_action,omitempty"`

	// (String) UUID.
	// UUID.
	OperationID *string `json:"operationId,omitempty" tf:"operation_id,omitempty"`

	// (String) Identifier.
	// Identifier.
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`
}

type SchemaValidationOperationSettingsParameters struct {

	// (String) When set, this applies a mitigation action to this operation
	// When set, this applies a mitigation action to this operation
	//
	// - `"log"` - log request when request does not conform to schema for this operation
	// - `"block"` - deny access to the site when request does not conform to schema for this operation
	// - `"none"` - will skip mitigation for this operation
	// - `null` - clears any mitigation action
	// Available values: "log", "block", "none".
	// +kubebuilder:validation:Optional
	MitigationAction *string `json:"mitigationAction,omitempty" tf:"mitigation_action,omitempty"`

	// (String) UUID.
	// UUID.
	// +kubebuilder:validation:Optional
	OperationID *string `json:"operationId,omitempty" tf:"operation_id,omitempty"`

	// (String) Identifier.
	// Identifier.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-cloudflare/apis/cluster/zone/v1alpha1.Zone
	// +kubebuilder:validation:Optional
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`

	// Reference to a Zone in zone to populate zoneId.
	// +kubebuilder:validation:Optional
	ZoneIDRef *v1.Reference `json:"zoneIdRef,omitempty" tf:"-"`

	// Selector for a Zone in zone to populate zoneId.
	// +kubebuilder:validation:Optional
	ZoneIDSelector *v1.Selector `json:"zoneIdSelector,omitempty" tf:"-"`
}

// SchemaValidationOperationSettingsSpec defines the desired state of SchemaValidationOperationSettings
type SchemaValidationOperationSettingsSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     SchemaValidationOperationSettingsParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SchemaValidationOperationSettingsInitParameters `json:"initProvider,omitempty"`
}

// SchemaValidationOperationSettingsStatus defines the observed state of SchemaValidationOperationSettings.
type SchemaValidationOperationSettingsStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        SchemaValidationOperationSettingsObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// SchemaValidationOperationSettings is the Schema for the SchemaValidationOperationSettingss API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,cloudflare}
type SchemaValidationOperationSettings struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.mitigationAction) || (has(self.initProvider) && has(self.initProvider.mitigationAction))",message="spec.forProvider.mitigationAction is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.operationId) || (has(self.initProvider) && has(self.initProvider.operationId))",message="spec.forProvider.operationId is a required parameter"
	Spec   SchemaValidationOperationSettingsSpec   `json:"spec"`
	Status SchemaValidationOperationSettingsStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SchemaValidationOperationSettingsList contains a list of SchemaValidationOperationSettingss
type SchemaValidationOperationSettingsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SchemaValidationOperationSettings `json:"items"`
}

// Repository type metadata.
var (
	SchemaValidationOperationSettings_Kind             = "SchemaValidationOperationSettings"
	SchemaValidationOperationSettings_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: SchemaValidationOperationSettings_Kind}.String()
	SchemaValidationOperationSettings_KindAPIVersion   = SchemaValidationOperationSettings_Kind + "." + CRDGroupVersion.String()
	SchemaValidationOperationSettings_GroupVersionKind = CRDGroupVersion.WithKind(SchemaValidationOperationSettings_Kind)
)

func init() {
	SchemeBuilder.Register(&SchemaValidationOperationSettings{}, &SchemaValidationOperationSettingsList{})
}
