// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type ZeroTrustDeviceDefaultProfileLocalDomainFallbackDomainsInitParameters struct {

	// (List of String) A list of IP addresses to handle domain resolution.
	// A list of IP addresses to handle domain resolution.
	DNSServer []*string `json:"dnsServer,omitempty" tf:"dns_server,omitempty"`

	// (String) A description of the fallback domain, displayed in the client UI.
	// A description of the fallback domain, displayed in the client UI.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The domain suffix to match when resolving locally.
	// The domain suffix to match when resolving locally.
	Suffix *string `json:"suffix,omitempty" tf:"suffix,omitempty"`
}

type ZeroTrustDeviceDefaultProfileLocalDomainFallbackDomainsObservation struct {

	// (List of String) A list of IP addresses to handle domain resolution.
	// A list of IP addresses to handle domain resolution.
	DNSServer []*string `json:"dnsServer,omitempty" tf:"dns_server,omitempty"`

	// (String) A description of the fallback domain, displayed in the client UI.
	// A description of the fallback domain, displayed in the client UI.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The domain suffix to match when resolving locally.
	// The domain suffix to match when resolving locally.
	Suffix *string `json:"suffix,omitempty" tf:"suffix,omitempty"`
}

type ZeroTrustDeviceDefaultProfileLocalDomainFallbackDomainsParameters struct {

	// (List of String) A list of IP addresses to handle domain resolution.
	// A list of IP addresses to handle domain resolution.
	// +kubebuilder:validation:Optional
	DNSServer []*string `json:"dnsServer,omitempty" tf:"dns_server,omitempty"`

	// (String) A description of the fallback domain, displayed in the client UI.
	// A description of the fallback domain, displayed in the client UI.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The domain suffix to match when resolving locally.
	// The domain suffix to match when resolving locally.
	// +kubebuilder:validation:Optional
	Suffix *string `json:"suffix" tf:"suffix,omitempty"`
}

type ZeroTrustDeviceDefaultProfileLocalDomainFallbackInitParameters struct {

	// (String)
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-cloudflare/apis/cluster/account/v1alpha1.Account
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// Reference to a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDRef *v1.Reference `json:"accountIdRef,omitempty" tf:"-"`

	// Selector for a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDSelector *v1.Selector `json:"accountIdSelector,omitempty" tf:"-"`

	// (Attributes List) (see below for nested schema)
	Domains []ZeroTrustDeviceDefaultProfileLocalDomainFallbackDomainsInitParameters `json:"domains,omitempty" tf:"domains,omitempty"`
}

type ZeroTrustDeviceDefaultProfileLocalDomainFallbackObservation struct {

	// (String)
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// (Attributes List) (see below for nested schema)
	Domains []ZeroTrustDeviceDefaultProfileLocalDomainFallbackDomainsObservation `json:"domains,omitempty" tf:"domains,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type ZeroTrustDeviceDefaultProfileLocalDomainFallbackParameters struct {

	// (String)
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-cloudflare/apis/cluster/account/v1alpha1.Account
	// +kubebuilder:validation:Optional
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// Reference to a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDRef *v1.Reference `json:"accountIdRef,omitempty" tf:"-"`

	// Selector for a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDSelector *v1.Selector `json:"accountIdSelector,omitempty" tf:"-"`

	// (Attributes List) (see below for nested schema)
	// +kubebuilder:validation:Optional
	Domains []ZeroTrustDeviceDefaultProfileLocalDomainFallbackDomainsParameters `json:"domains,omitempty" tf:"domains,omitempty"`
}

// ZeroTrustDeviceDefaultProfileLocalDomainFallbackSpec defines the desired state of ZeroTrustDeviceDefaultProfileLocalDomainFallback
type ZeroTrustDeviceDefaultProfileLocalDomainFallbackSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ZeroTrustDeviceDefaultProfileLocalDomainFallbackParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ZeroTrustDeviceDefaultProfileLocalDomainFallbackInitParameters `json:"initProvider,omitempty"`
}

// ZeroTrustDeviceDefaultProfileLocalDomainFallbackStatus defines the observed state of ZeroTrustDeviceDefaultProfileLocalDomainFallback.
type ZeroTrustDeviceDefaultProfileLocalDomainFallbackStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ZeroTrustDeviceDefaultProfileLocalDomainFallbackObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ZeroTrustDeviceDefaultProfileLocalDomainFallback is the Schema for the ZeroTrustDeviceDefaultProfileLocalDomainFallbacks API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,cloudflare}
type ZeroTrustDeviceDefaultProfileLocalDomainFallback struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.domains) || (has(self.initProvider) && has(self.initProvider.domains))",message="spec.forProvider.domains is a required parameter"
	Spec   ZeroTrustDeviceDefaultProfileLocalDomainFallbackSpec   `json:"spec"`
	Status ZeroTrustDeviceDefaultProfileLocalDomainFallbackStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ZeroTrustDeviceDefaultProfileLocalDomainFallbackList contains a list of ZeroTrustDeviceDefaultProfileLocalDomainFallbacks
type ZeroTrustDeviceDefaultProfileLocalDomainFallbackList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ZeroTrustDeviceDefaultProfileLocalDomainFallback `json:"items"`
}

// Repository type metadata.
var (
	ZeroTrustDeviceDefaultProfileLocalDomainFallback_Kind             = "ZeroTrustDeviceDefaultProfileLocalDomainFallback"
	ZeroTrustDeviceDefaultProfileLocalDomainFallback_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ZeroTrustDeviceDefaultProfileLocalDomainFallback_Kind}.String()
	ZeroTrustDeviceDefaultProfileLocalDomainFallback_KindAPIVersion   = ZeroTrustDeviceDefaultProfileLocalDomainFallback_Kind + "." + CRDGroupVersion.String()
	ZeroTrustDeviceDefaultProfileLocalDomainFallback_GroupVersionKind = CRDGroupVersion.WithKind(ZeroTrustDeviceDefaultProfileLocalDomainFallback_Kind)
)

func init() {
	SchemeBuilder.Register(&ZeroTrustDeviceDefaultProfileLocalDomainFallback{}, &ZeroTrustDeviceDefaultProfileLocalDomainFallbackList{})
}
