// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type EmailSecurityBlockSenderInitParameters struct {

	// (String) Account Identifier
	// Account Identifier
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-cloudflare/apis/cluster/account/v1alpha1.Account
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// Reference to a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDRef *v1.Reference `json:"accountIdRef,omitempty" tf:"-"`

	// Selector for a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDSelector *v1.Selector `json:"accountIdSelector,omitempty" tf:"-"`

	// (String)
	Comments *string `json:"comments,omitempty" tf:"comments,omitempty"`

	// (Boolean)
	IsRegex *bool `json:"isRegex,omitempty" tf:"is_regex,omitempty"`

	// (String)
	Pattern *string `json:"pattern,omitempty" tf:"pattern,omitempty"`

	// (String) Available values: "EMAIL", "DOMAIN", "IP", "UNKNOWN".
	// Available values: "EMAIL", "DOMAIN", "IP", "UNKNOWN".
	PatternType *string `json:"patternType,omitempty" tf:"pattern_type,omitempty"`
}

type EmailSecurityBlockSenderObservation struct {

	// (String) Account Identifier
	// Account Identifier
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// (String)
	Comments *string `json:"comments,omitempty" tf:"comments,omitempty"`

	// (String)
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// (Number) The unique identifier for the allow policy.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Boolean)
	IsRegex *bool `json:"isRegex,omitempty" tf:"is_regex,omitempty"`

	// (String)
	LastModified *string `json:"lastModified,omitempty" tf:"last_modified,omitempty"`

	// (String)
	Pattern *string `json:"pattern,omitempty" tf:"pattern,omitempty"`

	// (String) Available values: "EMAIL", "DOMAIN", "IP", "UNKNOWN".
	// Available values: "EMAIL", "DOMAIN", "IP", "UNKNOWN".
	PatternType *string `json:"patternType,omitempty" tf:"pattern_type,omitempty"`
}

type EmailSecurityBlockSenderParameters struct {

	// (String) Account Identifier
	// Account Identifier
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-cloudflare/apis/cluster/account/v1alpha1.Account
	// +kubebuilder:validation:Optional
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// Reference to a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDRef *v1.Reference `json:"accountIdRef,omitempty" tf:"-"`

	// Selector for a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDSelector *v1.Selector `json:"accountIdSelector,omitempty" tf:"-"`

	// (String)
	// +kubebuilder:validation:Optional
	Comments *string `json:"comments,omitempty" tf:"comments,omitempty"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	IsRegex *bool `json:"isRegex,omitempty" tf:"is_regex,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Pattern *string `json:"pattern,omitempty" tf:"pattern,omitempty"`

	// (String) Available values: "EMAIL", "DOMAIN", "IP", "UNKNOWN".
	// Available values: "EMAIL", "DOMAIN", "IP", "UNKNOWN".
	// +kubebuilder:validation:Optional
	PatternType *string `json:"patternType,omitempty" tf:"pattern_type,omitempty"`
}

// EmailSecurityBlockSenderSpec defines the desired state of EmailSecurityBlockSender
type EmailSecurityBlockSenderSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     EmailSecurityBlockSenderParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider EmailSecurityBlockSenderInitParameters `json:"initProvider,omitempty"`
}

// EmailSecurityBlockSenderStatus defines the observed state of EmailSecurityBlockSender.
type EmailSecurityBlockSenderStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        EmailSecurityBlockSenderObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// EmailSecurityBlockSender is the Schema for the EmailSecurityBlockSenders API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,cloudflare}
type EmailSecurityBlockSender struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.isRegex) || (has(self.initProvider) && has(self.initProvider.isRegex))",message="spec.forProvider.isRegex is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.pattern) || (has(self.initProvider) && has(self.initProvider.pattern))",message="spec.forProvider.pattern is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.patternType) || (has(self.initProvider) && has(self.initProvider.patternType))",message="spec.forProvider.patternType is a required parameter"
	Spec   EmailSecurityBlockSenderSpec   `json:"spec"`
	Status EmailSecurityBlockSenderStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// EmailSecurityBlockSenderList contains a list of EmailSecurityBlockSenders
type EmailSecurityBlockSenderList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []EmailSecurityBlockSender `json:"items"`
}

// Repository type metadata.
var (
	EmailSecurityBlockSender_Kind             = "EmailSecurityBlockSender"
	EmailSecurityBlockSender_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: EmailSecurityBlockSender_Kind}.String()
	EmailSecurityBlockSender_KindAPIVersion   = EmailSecurityBlockSender_Kind + "." + CRDGroupVersion.String()
	EmailSecurityBlockSender_GroupVersionKind = CRDGroupVersion.WithKind(EmailSecurityBlockSender_Kind)
)

func init() {
	SchemeBuilder.Register(&EmailSecurityBlockSender{}, &EmailSecurityBlockSenderList{})
}
