// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type APIShieldDiscoveryOperationInitParameters struct {

	// (String) UUID.
	// UUID.
	OperationID *string `json:"operationId,omitempty" tf:"operation_id,omitempty"`

	// (String) Mark state of operation in API Discovery
	// Mark state of operation in API Discovery
	// * `review` - Mark operation as for review
	// * `ignored` - Mark operation as ignored
	// Available values: "review", "ignored".
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// (String) Identifier.
	// Identifier.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-cloudflare/apis/namespaced/zone/v1alpha1.Zone
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`

	// Reference to a Zone in zone to populate zoneId.
	// +kubebuilder:validation:Optional
	ZoneIDRef *v1.NamespacedReference `json:"zoneIdRef,omitempty" tf:"-"`

	// Selector for a Zone in zone to populate zoneId.
	// +kubebuilder:validation:Optional
	ZoneIDSelector *v1.NamespacedSelector `json:"zoneIdSelector,omitempty" tf:"-"`
}

type APIShieldDiscoveryOperationObservation struct {

	// (String) UUID.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) UUID.
	// UUID.
	OperationID *string `json:"operationId,omitempty" tf:"operation_id,omitempty"`

	// (String) Mark state of operation in API Discovery
	// Mark state of operation in API Discovery
	// * `review` - Mark operation as for review
	// * `ignored` - Mark operation as ignored
	// Available values: "review", "ignored".
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// (String) Identifier.
	// Identifier.
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`
}

type APIShieldDiscoveryOperationParameters struct {

	// (String) UUID.
	// UUID.
	// +kubebuilder:validation:Optional
	OperationID *string `json:"operationId,omitempty" tf:"operation_id,omitempty"`

	// (String) Mark state of operation in API Discovery
	// Mark state of operation in API Discovery
	// * `review` - Mark operation as for review
	// * `ignored` - Mark operation as ignored
	// Available values: "review", "ignored".
	// +kubebuilder:validation:Optional
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// (String) Identifier.
	// Identifier.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-cloudflare/apis/namespaced/zone/v1alpha1.Zone
	// +kubebuilder:validation:Optional
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`

	// Reference to a Zone in zone to populate zoneId.
	// +kubebuilder:validation:Optional
	ZoneIDRef *v1.NamespacedReference `json:"zoneIdRef,omitempty" tf:"-"`

	// Selector for a Zone in zone to populate zoneId.
	// +kubebuilder:validation:Optional
	ZoneIDSelector *v1.NamespacedSelector `json:"zoneIdSelector,omitempty" tf:"-"`
}

// APIShieldDiscoveryOperationSpec defines the desired state of APIShieldDiscoveryOperation
type APIShieldDiscoveryOperationSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            APIShieldDiscoveryOperationParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider APIShieldDiscoveryOperationInitParameters `json:"initProvider,omitempty"`
}

// APIShieldDiscoveryOperationStatus defines the observed state of APIShieldDiscoveryOperation.
type APIShieldDiscoveryOperationStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        APIShieldDiscoveryOperationObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// APIShieldDiscoveryOperation is the Schema for the APIShieldDiscoveryOperations API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,cloudflare}
type APIShieldDiscoveryOperation struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.operationId) || (has(self.initProvider) && has(self.initProvider.operationId))",message="spec.forProvider.operationId is a required parameter"
	Spec   APIShieldDiscoveryOperationSpec   `json:"spec"`
	Status APIShieldDiscoveryOperationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// APIShieldDiscoveryOperationList contains a list of APIShieldDiscoveryOperations
type APIShieldDiscoveryOperationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []APIShieldDiscoveryOperation `json:"items"`
}

// Repository type metadata.
var (
	APIShieldDiscoveryOperation_Kind             = "APIShieldDiscoveryOperation"
	APIShieldDiscoveryOperation_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: APIShieldDiscoveryOperation_Kind}.String()
	APIShieldDiscoveryOperation_KindAPIVersion   = APIShieldDiscoveryOperation_Kind + "." + CRDGroupVersion.String()
	APIShieldDiscoveryOperation_GroupVersionKind = CRDGroupVersion.WithKind(APIShieldDiscoveryOperation_Kind)
)

func init() {
	SchemeBuilder.Register(&APIShieldDiscoveryOperation{}, &APIShieldDiscoveryOperationList{})
}
