// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type DNSZoneTransfersPeerInitParameters struct {

	// (String)
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-cloudflare/apis/cluster/account/v1alpha1.Account
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// Reference to a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDRef *v1.Reference `json:"accountIdRef,omitempty" tf:"-"`

	// Selector for a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDSelector *v1.Selector `json:"accountIdSelector,omitempty" tf:"-"`

	// (String) IPv4/IPv6 address of primary or secondary nameserver, depending on what zone this peer is linked to. For primary zones this IP defines the IP of the secondary nameserver Cloudflare will NOTIFY upon zone changes. For secondary zones this IP defines the IP of the primary nameserver Cloudflare will send AXFR/IXFR requests to.
	// IPv4/IPv6 address of primary or secondary nameserver, depending on what zone this peer is linked to. For primary zones this IP defines the IP of the secondary nameserver Cloudflare will NOTIFY upon zone changes. For secondary zones this IP defines the IP of the primary nameserver Cloudflare will send AXFR/IXFR requests to.
	IP *string `json:"ip,omitempty" tf:"ip,omitempty"`

	// (Boolean) Enable IXFR transfer protocol, default is AXFR. Only applicable to secondary zones.
	// Enable IXFR transfer protocol, default is AXFR. Only applicable to secondary zones.
	IxfrEnable *bool `json:"ixfrEnable,omitempty" tf:"ixfr_enable,omitempty"`

	// (String) The name of the peer.
	// The name of the peer.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) DNS port of primary or secondary nameserver, depending on what zone this peer is linked to.
	// DNS port of primary or secondary nameserver, depending on what zone this peer is linked to.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// (String) TSIG authentication will be used for zone transfer if configured.
	// TSIG authentication will be used for zone transfer if configured.
	TsigID *string `json:"tsigId,omitempty" tf:"tsig_id,omitempty"`
}

type DNSZoneTransfersPeerObservation struct {

	// (String)
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) IPv4/IPv6 address of primary or secondary nameserver, depending on what zone this peer is linked to. For primary zones this IP defines the IP of the secondary nameserver Cloudflare will NOTIFY upon zone changes. For secondary zones this IP defines the IP of the primary nameserver Cloudflare will send AXFR/IXFR requests to.
	// IPv4/IPv6 address of primary or secondary nameserver, depending on what zone this peer is linked to. For primary zones this IP defines the IP of the secondary nameserver Cloudflare will NOTIFY upon zone changes. For secondary zones this IP defines the IP of the primary nameserver Cloudflare will send AXFR/IXFR requests to.
	IP *string `json:"ip,omitempty" tf:"ip,omitempty"`

	// (Boolean) Enable IXFR transfer protocol, default is AXFR. Only applicable to secondary zones.
	// Enable IXFR transfer protocol, default is AXFR. Only applicable to secondary zones.
	IxfrEnable *bool `json:"ixfrEnable,omitempty" tf:"ixfr_enable,omitempty"`

	// (String) The name of the peer.
	// The name of the peer.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) DNS port of primary or secondary nameserver, depending on what zone this peer is linked to.
	// DNS port of primary or secondary nameserver, depending on what zone this peer is linked to.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// (String) TSIG authentication will be used for zone transfer if configured.
	// TSIG authentication will be used for zone transfer if configured.
	TsigID *string `json:"tsigId,omitempty" tf:"tsig_id,omitempty"`
}

type DNSZoneTransfersPeerParameters struct {

	// (String)
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-cloudflare/apis/cluster/account/v1alpha1.Account
	// +kubebuilder:validation:Optional
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// Reference to a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDRef *v1.Reference `json:"accountIdRef,omitempty" tf:"-"`

	// Selector for a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDSelector *v1.Selector `json:"accountIdSelector,omitempty" tf:"-"`

	// (String) IPv4/IPv6 address of primary or secondary nameserver, depending on what zone this peer is linked to. For primary zones this IP defines the IP of the secondary nameserver Cloudflare will NOTIFY upon zone changes. For secondary zones this IP defines the IP of the primary nameserver Cloudflare will send AXFR/IXFR requests to.
	// IPv4/IPv6 address of primary or secondary nameserver, depending on what zone this peer is linked to. For primary zones this IP defines the IP of the secondary nameserver Cloudflare will NOTIFY upon zone changes. For secondary zones this IP defines the IP of the primary nameserver Cloudflare will send AXFR/IXFR requests to.
	// +kubebuilder:validation:Optional
	IP *string `json:"ip,omitempty" tf:"ip,omitempty"`

	// (Boolean) Enable IXFR transfer protocol, default is AXFR. Only applicable to secondary zones.
	// Enable IXFR transfer protocol, default is AXFR. Only applicable to secondary zones.
	// +kubebuilder:validation:Optional
	IxfrEnable *bool `json:"ixfrEnable,omitempty" tf:"ixfr_enable,omitempty"`

	// (String) The name of the peer.
	// The name of the peer.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) DNS port of primary or secondary nameserver, depending on what zone this peer is linked to.
	// DNS port of primary or secondary nameserver, depending on what zone this peer is linked to.
	// +kubebuilder:validation:Optional
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// (String) TSIG authentication will be used for zone transfer if configured.
	// TSIG authentication will be used for zone transfer if configured.
	// +kubebuilder:validation:Optional
	TsigID *string `json:"tsigId,omitempty" tf:"tsig_id,omitempty"`
}

// DNSZoneTransfersPeerSpec defines the desired state of DNSZoneTransfersPeer
type DNSZoneTransfersPeerSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     DNSZoneTransfersPeerParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider DNSZoneTransfersPeerInitParameters `json:"initProvider,omitempty"`
}

// DNSZoneTransfersPeerStatus defines the observed state of DNSZoneTransfersPeer.
type DNSZoneTransfersPeerStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        DNSZoneTransfersPeerObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// DNSZoneTransfersPeer is the Schema for the DNSZoneTransfersPeers API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,cloudflare}
type DNSZoneTransfersPeer struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   DNSZoneTransfersPeerSpec   `json:"spec"`
	Status DNSZoneTransfersPeerStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DNSZoneTransfersPeerList contains a list of DNSZoneTransfersPeers
type DNSZoneTransfersPeerList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DNSZoneTransfersPeer `json:"items"`
}

// Repository type metadata.
var (
	DNSZoneTransfersPeer_Kind             = "DNSZoneTransfersPeer"
	DNSZoneTransfersPeer_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: DNSZoneTransfersPeer_Kind}.String()
	DNSZoneTransfersPeer_KindAPIVersion   = DNSZoneTransfersPeer_Kind + "." + CRDGroupVersion.String()
	DNSZoneTransfersPeer_GroupVersionKind = CRDGroupVersion.WithKind(DNSZoneTransfersPeer_Kind)
)

func init() {
	SchemeBuilder.Register(&DNSZoneTransfersPeer{}, &DNSZoneTransfersPeerList{})
}
