// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type PageShieldPolicyInitParameters struct {

	// (String) The action to take if the expression matches
	// Available values: "allow", "log".
	// The action to take if the expression matches
	// Available values: "allow", "log".
	Action *string `json:"action,omitempty" tf:"action,omitempty"`

	// (String) A description for the policy
	// A description for the policy
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Boolean) Whether the policy is enabled
	// Whether the policy is enabled
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) The expression which must match for the policy to be applied, using the Cloudflare Firewall rule expression syntax
	// The expression which must match for the policy to be applied, using the Cloudflare Firewall rule expression syntax
	Expression *string `json:"expression,omitempty" tf:"expression,omitempty"`

	// (String) The policy which will be applied
	// The policy which will be applied
	Value *string `json:"value,omitempty" tf:"value,omitempty"`

	// (String) Identifier
	// Identifier
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-cloudflare/apis/namespaced/zone/v1alpha1.Zone
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`

	// Reference to a Zone in zone to populate zoneId.
	// +kubebuilder:validation:Optional
	ZoneIDRef *v1.NamespacedReference `json:"zoneIdRef,omitempty" tf:"-"`

	// Selector for a Zone in zone to populate zoneId.
	// +kubebuilder:validation:Optional
	ZoneIDSelector *v1.NamespacedSelector `json:"zoneIdSelector,omitempty" tf:"-"`
}

type PageShieldPolicyObservation struct {

	// (String) The action to take if the expression matches
	// Available values: "allow", "log".
	// The action to take if the expression matches
	// Available values: "allow", "log".
	Action *string `json:"action,omitempty" tf:"action,omitempty"`

	// (String) A description for the policy
	// A description for the policy
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Boolean) Whether the policy is enabled
	// Whether the policy is enabled
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) The expression which must match for the policy to be applied, using the Cloudflare Firewall rule expression syntax
	// The expression which must match for the policy to be applied, using the Cloudflare Firewall rule expression syntax
	Expression *string `json:"expression,omitempty" tf:"expression,omitempty"`

	// (String) Identifier
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The policy which will be applied
	// The policy which will be applied
	Value *string `json:"value,omitempty" tf:"value,omitempty"`

	// (String) Identifier
	// Identifier
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`
}

type PageShieldPolicyParameters struct {

	// (String) The action to take if the expression matches
	// Available values: "allow", "log".
	// The action to take if the expression matches
	// Available values: "allow", "log".
	// +kubebuilder:validation:Optional
	Action *string `json:"action,omitempty" tf:"action,omitempty"`

	// (String) A description for the policy
	// A description for the policy
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Boolean) Whether the policy is enabled
	// Whether the policy is enabled
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) The expression which must match for the policy to be applied, using the Cloudflare Firewall rule expression syntax
	// The expression which must match for the policy to be applied, using the Cloudflare Firewall rule expression syntax
	// +kubebuilder:validation:Optional
	Expression *string `json:"expression,omitempty" tf:"expression,omitempty"`

	// (String) The policy which will be applied
	// The policy which will be applied
	// +kubebuilder:validation:Optional
	Value *string `json:"value,omitempty" tf:"value,omitempty"`

	// (String) Identifier
	// Identifier
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-cloudflare/apis/namespaced/zone/v1alpha1.Zone
	// +kubebuilder:validation:Optional
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`

	// Reference to a Zone in zone to populate zoneId.
	// +kubebuilder:validation:Optional
	ZoneIDRef *v1.NamespacedReference `json:"zoneIdRef,omitempty" tf:"-"`

	// Selector for a Zone in zone to populate zoneId.
	// +kubebuilder:validation:Optional
	ZoneIDSelector *v1.NamespacedSelector `json:"zoneIdSelector,omitempty" tf:"-"`
}

// PageShieldPolicySpec defines the desired state of PageShieldPolicy
type PageShieldPolicySpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            PageShieldPolicyParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider PageShieldPolicyInitParameters `json:"initProvider,omitempty"`
}

// PageShieldPolicyStatus defines the observed state of PageShieldPolicy.
type PageShieldPolicyStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        PageShieldPolicyObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// PageShieldPolicy is the Schema for the PageShieldPolicys API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,cloudflare}
type PageShieldPolicy struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.action) || (has(self.initProvider) && has(self.initProvider.action))",message="spec.forProvider.action is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.description) || (has(self.initProvider) && has(self.initProvider.description))",message="spec.forProvider.description is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.enabled) || (has(self.initProvider) && has(self.initProvider.enabled))",message="spec.forProvider.enabled is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.expression) || (has(self.initProvider) && has(self.initProvider.expression))",message="spec.forProvider.expression is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.value) || (has(self.initProvider) && has(self.initProvider.value))",message="spec.forProvider.value is a required parameter"
	Spec   PageShieldPolicySpec   `json:"spec"`
	Status PageShieldPolicyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PageShieldPolicyList contains a list of PageShieldPolicys
type PageShieldPolicyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []PageShieldPolicy `json:"items"`
}

// Repository type metadata.
var (
	PageShieldPolicy_Kind             = "PageShieldPolicy"
	PageShieldPolicy_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: PageShieldPolicy_Kind}.String()
	PageShieldPolicy_KindAPIVersion   = PageShieldPolicy_Kind + "." + CRDGroupVersion.String()
	PageShieldPolicy_GroupVersionKind = CRDGroupVersion.WithKind(PageShieldPolicy_Kind)
)

func init() {
	SchemeBuilder.Register(&PageShieldPolicy{}, &PageShieldPolicyList{})
}
