apiVersion: workers.cloudflare.m.cloudflare.com/v1alpha1
kind: WorkersCustomDomain
metadata:
  annotations:
    meta.upbound.io/example-id: workers/v1alpha1/workerscustomdomain
  labels:
    testing.upbound.io/example-name: example_workers_custom_domain
  name: example-workers-custom-domain
  namespace: crossplane-system
spec:
  forProvider:
    accountIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    environment: production
    hostname: foo.example.com
    service: foo
    zoneIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
