apiVersion: workers.cloudflare.crossplane.io/v1alpha1
kind: Workflow
metadata:
  annotations:
    meta.upbound.io/example-id: workers/v1alpha1/workflow
  labels:
    testing.upbound.io/example-name: example_workflow
  name: example-workflow
spec:
  forProvider:
    accountIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    className: x
    scriptName: x
    workflowName: x
