// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type ArgoSmartRoutingInitParameters struct {

	// (String) Specifies the enablement value of Argo Smart Routing.
	// Available values: "on", "off".
	// Specifies the enablement value of Argo Smart Routing.
	// Available values: "on", "off".
	Value *string `json:"value,omitempty" tf:"value,omitempty"`

	// (String) Specifies the zone associated with the API call.
	// Specifies the zone associated with the API call.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-cloudflare/apis/namespaced/zone/v1alpha1.Zone
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`

	// Reference to a Zone in zone to populate zoneId.
	// +kubebuilder:validation:Optional
	ZoneIDRef *v1.NamespacedReference `json:"zoneIdRef,omitempty" tf:"-"`

	// Selector for a Zone in zone to populate zoneId.
	// +kubebuilder:validation:Optional
	ZoneIDSelector *v1.NamespacedSelector `json:"zoneIdSelector,omitempty" tf:"-"`
}

type ArgoSmartRoutingObservation struct {

	// (Boolean) Specifies if the setting is editable.
	// Specifies if the setting is editable.
	Editable *bool `json:"editable,omitempty" tf:"editable,omitempty"`

	// (String) Specifies the zone associated with the API call.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Specifies the time when the setting was last modified.
	// Specifies the time when the setting was last modified.
	ModifiedOn *string `json:"modifiedOn,omitempty" tf:"modified_on,omitempty"`

	// (String) Specifies the enablement value of Argo Smart Routing.
	// Available values: "on", "off".
	// Specifies the enablement value of Argo Smart Routing.
	// Available values: "on", "off".
	Value *string `json:"value,omitempty" tf:"value,omitempty"`

	// (String) Specifies the zone associated with the API call.
	// Specifies the zone associated with the API call.
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`
}

type ArgoSmartRoutingParameters struct {

	// (String) Specifies the enablement value of Argo Smart Routing.
	// Available values: "on", "off".
	// Specifies the enablement value of Argo Smart Routing.
	// Available values: "on", "off".
	// +kubebuilder:validation:Optional
	Value *string `json:"value,omitempty" tf:"value,omitempty"`

	// (String) Specifies the zone associated with the API call.
	// Specifies the zone associated with the API call.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-cloudflare/apis/namespaced/zone/v1alpha1.Zone
	// +kubebuilder:validation:Optional
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`

	// Reference to a Zone in zone to populate zoneId.
	// +kubebuilder:validation:Optional
	ZoneIDRef *v1.NamespacedReference `json:"zoneIdRef,omitempty" tf:"-"`

	// Selector for a Zone in zone to populate zoneId.
	// +kubebuilder:validation:Optional
	ZoneIDSelector *v1.NamespacedSelector `json:"zoneIdSelector,omitempty" tf:"-"`
}

// ArgoSmartRoutingSpec defines the desired state of ArgoSmartRouting
type ArgoSmartRoutingSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ArgoSmartRoutingParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ArgoSmartRoutingInitParameters `json:"initProvider,omitempty"`
}

// ArgoSmartRoutingStatus defines the observed state of ArgoSmartRouting.
type ArgoSmartRoutingStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ArgoSmartRoutingObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ArgoSmartRouting is the Schema for the ArgoSmartRoutings API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,cloudflare}
type ArgoSmartRouting struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.value) || (has(self.initProvider) && has(self.initProvider.value))",message="spec.forProvider.value is a required parameter"
	Spec   ArgoSmartRoutingSpec   `json:"spec"`
	Status ArgoSmartRoutingStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ArgoSmartRoutingList contains a list of ArgoSmartRoutings
type ArgoSmartRoutingList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ArgoSmartRouting `json:"items"`
}

// Repository type metadata.
var (
	ArgoSmartRouting_Kind             = "ArgoSmartRouting"
	ArgoSmartRouting_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ArgoSmartRouting_Kind}.String()
	ArgoSmartRouting_KindAPIVersion   = ArgoSmartRouting_Kind + "." + CRDGroupVersion.String()
	ArgoSmartRouting_GroupVersionKind = CRDGroupVersion.WithKind(ArgoSmartRouting_Kind)
)

func init() {
	SchemeBuilder.Register(&ArgoSmartRouting{}, &ArgoSmartRoutingList{})
}
