// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type Lan1InitParameters struct {

	// (String) The identifier for the LAN you want to create an ACL policy with.
	// The identifier for the LAN you want to create an ACL policy with.
	LanID *string `json:"lanId,omitempty" tf:"lan_id,omitempty"`

	// (String) The name of the LAN based on the provided lan_id.
	// The name of the LAN based on the provided lan_id.
	LanName *string `json:"lanName,omitempty" tf:"lan_name,omitempty"`

	// (List of String) Array of port ranges on the provided LAN that will be included in the ACL. If no ports or port rangess are provided, communication on any port on this LAN is allowed.
	// Array of port ranges on the provided LAN that will be included in the ACL. If no ports or port rangess are provided, communication on any port on this LAN is allowed.
	PortRanges []*string `json:"portRanges,omitempty" tf:"port_ranges,omitempty"`

	// (List of Number) Array of ports on the provided LAN that will be included in the ACL. If no ports or port ranges are provided, communication on any port on this LAN is allowed.
	// Array of ports on the provided LAN that will be included in the ACL. If no ports or port ranges are provided, communication on any port on this LAN is allowed.
	Ports []*float64 `json:"ports,omitempty" tf:"ports,omitempty"`

	// (List of String) Array of subnet IPs within the LAN that will be included in the ACL. If no subnets are provided, communication on any subnets on this LAN are allowed.
	// Array of subnet IPs within the LAN that will be included in the ACL. If no subnets are provided, communication on any subnets on this LAN are allowed.
	Subnets []*string `json:"subnets,omitempty" tf:"subnets,omitempty"`
}

type Lan1Observation struct {

	// (String) The identifier for the LAN you want to create an ACL policy with.
	// The identifier for the LAN you want to create an ACL policy with.
	LanID *string `json:"lanId,omitempty" tf:"lan_id,omitempty"`

	// (String) The name of the LAN based on the provided lan_id.
	// The name of the LAN based on the provided lan_id.
	LanName *string `json:"lanName,omitempty" tf:"lan_name,omitempty"`

	// (List of String) Array of port ranges on the provided LAN that will be included in the ACL. If no ports or port rangess are provided, communication on any port on this LAN is allowed.
	// Array of port ranges on the provided LAN that will be included in the ACL. If no ports or port rangess are provided, communication on any port on this LAN is allowed.
	PortRanges []*string `json:"portRanges,omitempty" tf:"port_ranges,omitempty"`

	// (List of Number) Array of ports on the provided LAN that will be included in the ACL. If no ports or port ranges are provided, communication on any port on this LAN is allowed.
	// Array of ports on the provided LAN that will be included in the ACL. If no ports or port ranges are provided, communication on any port on this LAN is allowed.
	Ports []*float64 `json:"ports,omitempty" tf:"ports,omitempty"`

	// (List of String) Array of subnet IPs within the LAN that will be included in the ACL. If no subnets are provided, communication on any subnets on this LAN are allowed.
	// Array of subnet IPs within the LAN that will be included in the ACL. If no subnets are provided, communication on any subnets on this LAN are allowed.
	Subnets []*string `json:"subnets,omitempty" tf:"subnets,omitempty"`
}

type Lan1Parameters struct {

	// (String) The identifier for the LAN you want to create an ACL policy with.
	// The identifier for the LAN you want to create an ACL policy with.
	// +kubebuilder:validation:Optional
	LanID *string `json:"lanId" tf:"lan_id,omitempty"`

	// (String) The name of the LAN based on the provided lan_id.
	// The name of the LAN based on the provided lan_id.
	// +kubebuilder:validation:Optional
	LanName *string `json:"lanName,omitempty" tf:"lan_name,omitempty"`

	// (List of String) Array of port ranges on the provided LAN that will be included in the ACL. If no ports or port rangess are provided, communication on any port on this LAN is allowed.
	// Array of port ranges on the provided LAN that will be included in the ACL. If no ports or port rangess are provided, communication on any port on this LAN is allowed.
	// +kubebuilder:validation:Optional
	PortRanges []*string `json:"portRanges,omitempty" tf:"port_ranges,omitempty"`

	// (List of Number) Array of ports on the provided LAN that will be included in the ACL. If no ports or port ranges are provided, communication on any port on this LAN is allowed.
	// Array of ports on the provided LAN that will be included in the ACL. If no ports or port ranges are provided, communication on any port on this LAN is allowed.
	// +kubebuilder:validation:Optional
	Ports []*float64 `json:"ports,omitempty" tf:"ports,omitempty"`

	// (List of String) Array of subnet IPs within the LAN that will be included in the ACL. If no subnets are provided, communication on any subnets on this LAN are allowed.
	// Array of subnet IPs within the LAN that will be included in the ACL. If no subnets are provided, communication on any subnets on this LAN are allowed.
	// +kubebuilder:validation:Optional
	Subnets []*string `json:"subnets,omitempty" tf:"subnets,omitempty"`
}

type Lan2InitParameters struct {

	// (String) The identifier for the LAN you want to create an ACL policy with.
	// The identifier for the LAN you want to create an ACL policy with.
	LanID *string `json:"lanId,omitempty" tf:"lan_id,omitempty"`

	// (String) The name of the LAN based on the provided lan_id.
	// The name of the LAN based on the provided lan_id.
	LanName *string `json:"lanName,omitempty" tf:"lan_name,omitempty"`

	// (List of String) Array of port ranges on the provided LAN that will be included in the ACL. If no ports or port rangess are provided, communication on any port on this LAN is allowed.
	// Array of port ranges on the provided LAN that will be included in the ACL. If no ports or port rangess are provided, communication on any port on this LAN is allowed.
	PortRanges []*string `json:"portRanges,omitempty" tf:"port_ranges,omitempty"`

	// (List of Number) Array of ports on the provided LAN that will be included in the ACL. If no ports or port ranges are provided, communication on any port on this LAN is allowed.
	// Array of ports on the provided LAN that will be included in the ACL. If no ports or port ranges are provided, communication on any port on this LAN is allowed.
	Ports []*float64 `json:"ports,omitempty" tf:"ports,omitempty"`

	// (List of String) Array of subnet IPs within the LAN that will be included in the ACL. If no subnets are provided, communication on any subnets on this LAN are allowed.
	// Array of subnet IPs within the LAN that will be included in the ACL. If no subnets are provided, communication on any subnets on this LAN are allowed.
	Subnets []*string `json:"subnets,omitempty" tf:"subnets,omitempty"`
}

type Lan2Observation struct {

	// (String) The identifier for the LAN you want to create an ACL policy with.
	// The identifier for the LAN you want to create an ACL policy with.
	LanID *string `json:"lanId,omitempty" tf:"lan_id,omitempty"`

	// (String) The name of the LAN based on the provided lan_id.
	// The name of the LAN based on the provided lan_id.
	LanName *string `json:"lanName,omitempty" tf:"lan_name,omitempty"`

	// (List of String) Array of port ranges on the provided LAN that will be included in the ACL. If no ports or port rangess are provided, communication on any port on this LAN is allowed.
	// Array of port ranges on the provided LAN that will be included in the ACL. If no ports or port rangess are provided, communication on any port on this LAN is allowed.
	PortRanges []*string `json:"portRanges,omitempty" tf:"port_ranges,omitempty"`

	// (List of Number) Array of ports on the provided LAN that will be included in the ACL. If no ports or port ranges are provided, communication on any port on this LAN is allowed.
	// Array of ports on the provided LAN that will be included in the ACL. If no ports or port ranges are provided, communication on any port on this LAN is allowed.
	Ports []*float64 `json:"ports,omitempty" tf:"ports,omitempty"`

	// (List of String) Array of subnet IPs within the LAN that will be included in the ACL. If no subnets are provided, communication on any subnets on this LAN are allowed.
	// Array of subnet IPs within the LAN that will be included in the ACL. If no subnets are provided, communication on any subnets on this LAN are allowed.
	Subnets []*string `json:"subnets,omitempty" tf:"subnets,omitempty"`
}

type Lan2Parameters struct {

	// (String) The identifier for the LAN you want to create an ACL policy with.
	// The identifier for the LAN you want to create an ACL policy with.
	// +kubebuilder:validation:Optional
	LanID *string `json:"lanId" tf:"lan_id,omitempty"`

	// (String) The name of the LAN based on the provided lan_id.
	// The name of the LAN based on the provided lan_id.
	// +kubebuilder:validation:Optional
	LanName *string `json:"lanName,omitempty" tf:"lan_name,omitempty"`

	// (List of String) Array of port ranges on the provided LAN that will be included in the ACL. If no ports or port rangess are provided, communication on any port on this LAN is allowed.
	// Array of port ranges on the provided LAN that will be included in the ACL. If no ports or port rangess are provided, communication on any port on this LAN is allowed.
	// +kubebuilder:validation:Optional
	PortRanges []*string `json:"portRanges,omitempty" tf:"port_ranges,omitempty"`

	// (List of Number) Array of ports on the provided LAN that will be included in the ACL. If no ports or port ranges are provided, communication on any port on this LAN is allowed.
	// Array of ports on the provided LAN that will be included in the ACL. If no ports or port ranges are provided, communication on any port on this LAN is allowed.
	// +kubebuilder:validation:Optional
	Ports []*float64 `json:"ports,omitempty" tf:"ports,omitempty"`

	// (List of String) Array of subnet IPs within the LAN that will be included in the ACL. If no subnets are provided, communication on any subnets on this LAN are allowed.
	// Array of subnet IPs within the LAN that will be included in the ACL. If no subnets are provided, communication on any subnets on this LAN are allowed.
	// +kubebuilder:validation:Optional
	Subnets []*string `json:"subnets,omitempty" tf:"subnets,omitempty"`
}

type MagicTransitSiteACLInitParameters struct {

	// (String) Identifier
	// Identifier
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-cloudflare/apis/namespaced/account/v1alpha1.Account
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// Reference to a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDRef *v1.NamespacedReference `json:"accountIdRef,omitempty" tf:"-"`

	// Selector for a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDSelector *v1.NamespacedSelector `json:"accountIdSelector,omitempty" tf:"-"`

	// (String) Description for the ACL.
	// Description for the ACL.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Boolean) The desired forwarding action for this ACL policy. If set to "false", the policy will forward traffic to Cloudflare. If set to "true", the policy will forward traffic locally on the Magic Connector. If not included in request, will default to false.
	// The desired forwarding action for this ACL policy. If set to "false", the policy will forward traffic to Cloudflare. If set to "true", the policy will forward traffic locally on the Magic Connector. If not included in request, will default to false.
	ForwardLocally *bool `json:"forwardLocally,omitempty" tf:"forward_locally,omitempty"`

	// (Attributes) (see below for nested schema)
	Lan1 *Lan1InitParameters `json:"lan1,omitempty" tf:"lan_1,omitempty"`

	// (Attributes) (see below for nested schema)
	Lan2 *Lan2InitParameters `json:"lan2,omitempty" tf:"lan_2,omitempty"`

	// (String) The name of the ACL.
	// The name of the ACL.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (List of String)
	Protocols []*string `json:"protocols,omitempty" tf:"protocols,omitempty"`

	// (String) Identifier
	// Identifier
	SiteID *string `json:"siteId,omitempty" tf:"site_id,omitempty"`

	// (Boolean) The desired traffic direction for this ACL policy. If set to "false", the policy will allow bidirectional traffic. If set to "true", the policy will only allow traffic in one direction. If not included in request, will default to false.
	// The desired traffic direction for this ACL policy. If set to "false", the policy will allow bidirectional traffic. If set to "true", the policy will only allow traffic in one direction. If not included in request, will default to false.
	Unidirectional *bool `json:"unidirectional,omitempty" tf:"unidirectional,omitempty"`
}

type MagicTransitSiteACLObservation struct {

	// (String) Identifier
	// Identifier
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// (String) Description for the ACL.
	// Description for the ACL.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Boolean) The desired forwarding action for this ACL policy. If set to "false", the policy will forward traffic to Cloudflare. If set to "true", the policy will forward traffic locally on the Magic Connector. If not included in request, will default to false.
	// The desired forwarding action for this ACL policy. If set to "false", the policy will forward traffic to Cloudflare. If set to "true", the policy will forward traffic locally on the Magic Connector. If not included in request, will default to false.
	ForwardLocally *bool `json:"forwardLocally,omitempty" tf:"forward_locally,omitempty"`

	// (String) Identifier
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Attributes) (see below for nested schema)
	Lan1 *Lan1Observation `json:"lan1,omitempty" tf:"lan_1,omitempty"`

	// (Attributes) (see below for nested schema)
	Lan2 *Lan2Observation `json:"lan2,omitempty" tf:"lan_2,omitempty"`

	// (String) The name of the ACL.
	// The name of the ACL.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (List of String)
	Protocols []*string `json:"protocols,omitempty" tf:"protocols,omitempty"`

	// (String) Identifier
	// Identifier
	SiteID *string `json:"siteId,omitempty" tf:"site_id,omitempty"`

	// (Boolean) The desired traffic direction for this ACL policy. If set to "false", the policy will allow bidirectional traffic. If set to "true", the policy will only allow traffic in one direction. If not included in request, will default to false.
	// The desired traffic direction for this ACL policy. If set to "false", the policy will allow bidirectional traffic. If set to "true", the policy will only allow traffic in one direction. If not included in request, will default to false.
	Unidirectional *bool `json:"unidirectional,omitempty" tf:"unidirectional,omitempty"`
}

type MagicTransitSiteACLParameters struct {

	// (String) Identifier
	// Identifier
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-cloudflare/apis/namespaced/account/v1alpha1.Account
	// +kubebuilder:validation:Optional
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// Reference to a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDRef *v1.NamespacedReference `json:"accountIdRef,omitempty" tf:"-"`

	// Selector for a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDSelector *v1.NamespacedSelector `json:"accountIdSelector,omitempty" tf:"-"`

	// (String) Description for the ACL.
	// Description for the ACL.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Boolean) The desired forwarding action for this ACL policy. If set to "false", the policy will forward traffic to Cloudflare. If set to "true", the policy will forward traffic locally on the Magic Connector. If not included in request, will default to false.
	// The desired forwarding action for this ACL policy. If set to "false", the policy will forward traffic to Cloudflare. If set to "true", the policy will forward traffic locally on the Magic Connector. If not included in request, will default to false.
	// +kubebuilder:validation:Optional
	ForwardLocally *bool `json:"forwardLocally,omitempty" tf:"forward_locally,omitempty"`

	// (Attributes) (see below for nested schema)
	// +kubebuilder:validation:Optional
	Lan1 *Lan1Parameters `json:"lan1,omitempty" tf:"lan_1,omitempty"`

	// (Attributes) (see below for nested schema)
	// +kubebuilder:validation:Optional
	Lan2 *Lan2Parameters `json:"lan2,omitempty" tf:"lan_2,omitempty"`

	// (String) The name of the ACL.
	// The name of the ACL.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (List of String)
	// +kubebuilder:validation:Optional
	Protocols []*string `json:"protocols,omitempty" tf:"protocols,omitempty"`

	// (String) Identifier
	// Identifier
	// +kubebuilder:validation:Optional
	SiteID *string `json:"siteId,omitempty" tf:"site_id,omitempty"`

	// (Boolean) The desired traffic direction for this ACL policy. If set to "false", the policy will allow bidirectional traffic. If set to "true", the policy will only allow traffic in one direction. If not included in request, will default to false.
	// The desired traffic direction for this ACL policy. If set to "false", the policy will allow bidirectional traffic. If set to "true", the policy will only allow traffic in one direction. If not included in request, will default to false.
	// +kubebuilder:validation:Optional
	Unidirectional *bool `json:"unidirectional,omitempty" tf:"unidirectional,omitempty"`
}

// MagicTransitSiteACLSpec defines the desired state of MagicTransitSiteACL
type MagicTransitSiteACLSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            MagicTransitSiteACLParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider MagicTransitSiteACLInitParameters `json:"initProvider,omitempty"`
}

// MagicTransitSiteACLStatus defines the observed state of MagicTransitSiteACL.
type MagicTransitSiteACLStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        MagicTransitSiteACLObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// MagicTransitSiteACL is the Schema for the MagicTransitSiteACLs API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,cloudflare}
type MagicTransitSiteACL struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.lan1) || (has(self.initProvider) && has(self.initProvider.lan1))",message="spec.forProvider.lan1 is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.lan2) || (has(self.initProvider) && has(self.initProvider.lan2))",message="spec.forProvider.lan2 is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.siteId) || (has(self.initProvider) && has(self.initProvider.siteId))",message="spec.forProvider.siteId is a required parameter"
	Spec   MagicTransitSiteACLSpec   `json:"spec"`
	Status MagicTransitSiteACLStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// MagicTransitSiteACLList contains a list of MagicTransitSiteACLs
type MagicTransitSiteACLList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []MagicTransitSiteACL `json:"items"`
}

// Repository type metadata.
var (
	MagicTransitSiteACL_Kind             = "MagicTransitSiteACL"
	MagicTransitSiteACL_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: MagicTransitSiteACL_Kind}.String()
	MagicTransitSiteACL_KindAPIVersion   = MagicTransitSiteACL_Kind + "." + CRDGroupVersion.String()
	MagicTransitSiteACL_GroupVersionKind = CRDGroupVersion.WithKind(MagicTransitSiteACL_Kind)
)

func init() {
	SchemeBuilder.Register(&MagicTransitSiteACL{}, &MagicTransitSiteACLList{})
}
