// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type MagicNetworkMonitoringRuleInitParameters struct {

	// (String)
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-cloudflare/apis/namespaced/account/v1alpha1.Account
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// Reference to a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDRef *v1.NamespacedReference `json:"accountIdRef,omitempty" tf:"-"`

	// Selector for a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDSelector *v1.NamespacedSelector `json:"accountIdSelector,omitempty" tf:"-"`

	// (Boolean) Toggle on if you would like Cloudflare to automatically advertise the IP Prefixes within the rule via Magic Transit when the rule is triggered. Only available for users of Magic Transit.
	// Toggle on if you would like Cloudflare to automatically advertise the IP Prefixes within the rule via Magic Transit when the rule is triggered. Only available for users of Magic Transit.
	AutomaticAdvertisement *bool `json:"automaticAdvertisement,omitempty" tf:"automatic_advertisement,omitempty"`

	// (Number) The number of bits per second for the rule. When this value is exceeded for the set duration, an alert notification is sent. Minimum of 1 and no maximum.
	// The number of bits per second for the rule. When this value is exceeded for the set duration, an alert notification is sent. Minimum of 1 and no maximum.
	Bandwidth *float64 `json:"bandwidth,omitempty" tf:"bandwidth,omitempty"`

	// (String) The amount of time that the rule threshold must be exceeded to send an alert notification. The final value must be equivalent to one of the following 8 values ["1m","5m","10m","15m","20m","30m","45m","60m"].
	// Available values: "1m", "5m", "10m", "15m", "20m", "30m", "45m", "60m".
	// The amount of time that the rule threshold must be exceeded to send an alert notification. The final value must be equivalent to one of the following 8 values ["1m","5m","10m","15m","20m","30m","45m","60m"].
	// Available values: "1m", "5m", "10m", "15m", "20m", "30m", "45m", "60m".
	Duration *string `json:"duration,omitempty" tf:"duration,omitempty"`

	// Z, a-z, 0-9, underscore (_), dash (-), period (.), and tilde (~). You can’t have a space in the rule name. Max 256 characters.
	// The name of the rule. Must be unique. Supports characters A-Z, a-z, 0-9, underscore (_), dash (-), period (.), and tilde (~). You can’t have a space in the rule name. Max 256 characters.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) The number of packets per second for the rule. When this value is exceeded for the set duration, an alert notification is sent. Minimum of 1 and no maximum.
	// The number of packets per second for the rule. When this value is exceeded for the set duration, an alert notification is sent. Minimum of 1 and no maximum.
	PacketThreshold *float64 `json:"packetThreshold,omitempty" tf:"packet_threshold,omitempty"`

	// (List of String)
	Prefixes []*string `json:"prefixes,omitempty" tf:"prefixes,omitempty"`
}

type MagicNetworkMonitoringRuleObservation struct {

	// (String)
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// (Boolean) Toggle on if you would like Cloudflare to automatically advertise the IP Prefixes within the rule via Magic Transit when the rule is triggered. Only available for users of Magic Transit.
	// Toggle on if you would like Cloudflare to automatically advertise the IP Prefixes within the rule via Magic Transit when the rule is triggered. Only available for users of Magic Transit.
	AutomaticAdvertisement *bool `json:"automaticAdvertisement,omitempty" tf:"automatic_advertisement,omitempty"`

	// (Number) The number of bits per second for the rule. When this value is exceeded for the set duration, an alert notification is sent. Minimum of 1 and no maximum.
	// The number of bits per second for the rule. When this value is exceeded for the set duration, an alert notification is sent. Minimum of 1 and no maximum.
	Bandwidth *float64 `json:"bandwidth,omitempty" tf:"bandwidth,omitempty"`

	// (Number) The number of bits per second for the rule. When this value is exceeded for the set duration, an alert notification is sent. Minimum of 1 and no maximum.
	// The number of bits per second for the rule. When this value is exceeded for the set duration, an alert notification is sent. Minimum of 1 and no maximum.
	BandwidthThreshold *float64 `json:"bandwidthThreshold,omitempty" tf:"bandwidth_threshold,omitempty"`

	// (String) The amount of time that the rule threshold must be exceeded to send an alert notification. The final value must be equivalent to one of the following 8 values ["1m","5m","10m","15m","20m","30m","45m","60m"].
	// Available values: "1m", "5m", "10m", "15m", "20m", "30m", "45m", "60m".
	// The amount of time that the rule threshold must be exceeded to send an alert notification. The final value must be equivalent to one of the following 8 values ["1m","5m","10m","15m","20m","30m","45m","60m"].
	// Available values: "1m", "5m", "10m", "15m", "20m", "30m", "45m", "60m".
	Duration *string `json:"duration,omitempty" tf:"duration,omitempty"`

	// (String) The id of the rule. Must be unique.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Z, a-z, 0-9, underscore (_), dash (-), period (.), and tilde (~). You can’t have a space in the rule name. Max 256 characters.
	// The name of the rule. Must be unique. Supports characters A-Z, a-z, 0-9, underscore (_), dash (-), period (.), and tilde (~). You can’t have a space in the rule name. Max 256 characters.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) The number of packets per second for the rule. When this value is exceeded for the set duration, an alert notification is sent. Minimum of 1 and no maximum.
	// The number of packets per second for the rule. When this value is exceeded for the set duration, an alert notification is sent. Minimum of 1 and no maximum.
	PacketThreshold *float64 `json:"packetThreshold,omitempty" tf:"packet_threshold,omitempty"`

	// (String) Prefix match type to be applied for a prefix auto advertisement when using an advanced_ddos rule.
	// Available values: "exact", "subnet", "supernet".
	// Prefix match type to be applied for a prefix auto advertisement when using an advanced_ddos rule.
	// Available values: "exact", "subnet", "supernet".
	PrefixMatch *string `json:"prefixMatch,omitempty" tf:"prefix_match,omitempty"`

	// (List of String)
	Prefixes []*string `json:"prefixes,omitempty" tf:"prefixes,omitempty"`

	// (String) MNM rule type.
	// Available values: "threshold", "zscore", "advanced_ddos".
	// MNM rule type.
	// Available values: "threshold", "zscore", "advanced_ddos".
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String) Level of sensitivity set for zscore rules.
	// Available values: "low", "medium", "high".
	// Level of sensitivity set for zscore rules.
	// Available values: "low", "medium", "high".
	ZscoreSensitivity *string `json:"zscoreSensitivity,omitempty" tf:"zscore_sensitivity,omitempty"`

	// (String) Target of the zscore rule analysis.
	// Available values: "bits", "packets".
	// Target of the zscore rule analysis.
	// Available values: "bits", "packets".
	ZscoreTarget *string `json:"zscoreTarget,omitempty" tf:"zscore_target,omitempty"`
}

type MagicNetworkMonitoringRuleParameters struct {

	// (String)
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-cloudflare/apis/namespaced/account/v1alpha1.Account
	// +kubebuilder:validation:Optional
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// Reference to a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDRef *v1.NamespacedReference `json:"accountIdRef,omitempty" tf:"-"`

	// Selector for a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDSelector *v1.NamespacedSelector `json:"accountIdSelector,omitempty" tf:"-"`

	// (Boolean) Toggle on if you would like Cloudflare to automatically advertise the IP Prefixes within the rule via Magic Transit when the rule is triggered. Only available for users of Magic Transit.
	// Toggle on if you would like Cloudflare to automatically advertise the IP Prefixes within the rule via Magic Transit when the rule is triggered. Only available for users of Magic Transit.
	// +kubebuilder:validation:Optional
	AutomaticAdvertisement *bool `json:"automaticAdvertisement,omitempty" tf:"automatic_advertisement,omitempty"`

	// (Number) The number of bits per second for the rule. When this value is exceeded for the set duration, an alert notification is sent. Minimum of 1 and no maximum.
	// The number of bits per second for the rule. When this value is exceeded for the set duration, an alert notification is sent. Minimum of 1 and no maximum.
	// +kubebuilder:validation:Optional
	Bandwidth *float64 `json:"bandwidth,omitempty" tf:"bandwidth,omitempty"`

	// (String) The amount of time that the rule threshold must be exceeded to send an alert notification. The final value must be equivalent to one of the following 8 values ["1m","5m","10m","15m","20m","30m","45m","60m"].
	// Available values: "1m", "5m", "10m", "15m", "20m", "30m", "45m", "60m".
	// The amount of time that the rule threshold must be exceeded to send an alert notification. The final value must be equivalent to one of the following 8 values ["1m","5m","10m","15m","20m","30m","45m","60m"].
	// Available values: "1m", "5m", "10m", "15m", "20m", "30m", "45m", "60m".
	// +kubebuilder:validation:Optional
	Duration *string `json:"duration,omitempty" tf:"duration,omitempty"`

	// Z, a-z, 0-9, underscore (_), dash (-), period (.), and tilde (~). You can’t have a space in the rule name. Max 256 characters.
	// The name of the rule. Must be unique. Supports characters A-Z, a-z, 0-9, underscore (_), dash (-), period (.), and tilde (~). You can’t have a space in the rule name. Max 256 characters.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) The number of packets per second for the rule. When this value is exceeded for the set duration, an alert notification is sent. Minimum of 1 and no maximum.
	// The number of packets per second for the rule. When this value is exceeded for the set duration, an alert notification is sent. Minimum of 1 and no maximum.
	// +kubebuilder:validation:Optional
	PacketThreshold *float64 `json:"packetThreshold,omitempty" tf:"packet_threshold,omitempty"`

	// (List of String)
	// +kubebuilder:validation:Optional
	Prefixes []*string `json:"prefixes,omitempty" tf:"prefixes,omitempty"`
}

// MagicNetworkMonitoringRuleSpec defines the desired state of MagicNetworkMonitoringRule
type MagicNetworkMonitoringRuleSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            MagicNetworkMonitoringRuleParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider MagicNetworkMonitoringRuleInitParameters `json:"initProvider,omitempty"`
}

// MagicNetworkMonitoringRuleStatus defines the observed state of MagicNetworkMonitoringRule.
type MagicNetworkMonitoringRuleStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        MagicNetworkMonitoringRuleObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// MagicNetworkMonitoringRule is the Schema for the MagicNetworkMonitoringRules API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,cloudflare}
type MagicNetworkMonitoringRule struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   MagicNetworkMonitoringRuleSpec   `json:"spec"`
	Status MagicNetworkMonitoringRuleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// MagicNetworkMonitoringRuleList contains a list of MagicNetworkMonitoringRules
type MagicNetworkMonitoringRuleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []MagicNetworkMonitoringRule `json:"items"`
}

// Repository type metadata.
var (
	MagicNetworkMonitoringRule_Kind             = "MagicNetworkMonitoringRule"
	MagicNetworkMonitoringRule_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: MagicNetworkMonitoringRule_Kind}.String()
	MagicNetworkMonitoringRule_KindAPIVersion   = MagicNetworkMonitoringRule_Kind + "." + CRDGroupVersion.String()
	MagicNetworkMonitoringRule_GroupVersionKind = CRDGroupVersion.WithKind(MagicNetworkMonitoringRule_Kind)
)

func init() {
	SchemeBuilder.Register(&MagicNetworkMonitoringRule{}, &MagicNetworkMonitoringRuleList{})
}
