// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type ZeroTrustAccessAIControlsMCPServerInitParameters struct {

	// (String)
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-cloudflare/apis/cluster/account/v1alpha1.Account
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// Reference to a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDRef *v1.Reference `json:"accountIdRef,omitempty" tf:"-"`

	// Selector for a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDSelector *v1.Selector `json:"accountIdSelector,omitempty" tf:"-"`

	// (String)
	AuthCredentials *string `json:"authCredentials,omitempty" tf:"auth_credentials,omitempty"`

	// (String) Available values: "oauth", "bearer", "unauthenticated".
	// Available values: "oauth", "bearer", "unauthenticated".
	AuthType *string `json:"authType,omitempty" tf:"auth_type,omitempty"`

	// (String)
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String)
	Hostname *string `json:"hostname,omitempty" tf:"hostname,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type ZeroTrustAccessAIControlsMCPServerObservation struct {

	// (String)
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// (String)
	AuthCredentials *string `json:"authCredentials,omitempty" tf:"auth_credentials,omitempty"`

	// (String) Available values: "oauth", "bearer", "unauthenticated".
	// Available values: "oauth", "bearer", "unauthenticated".
	AuthType *string `json:"authType,omitempty" tf:"auth_type,omitempty"`

	// (String)
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// (String)
	CreatedBy *string `json:"createdBy,omitempty" tf:"created_by,omitempty"`

	// (String)
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String)
	Error *string `json:"error,omitempty" tf:"error,omitempty"`

	// (String)
	Hostname *string `json:"hostname,omitempty" tf:"hostname,omitempty"`

	// (String) server id
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String)
	LastSynced *string `json:"lastSynced,omitempty" tf:"last_synced,omitempty"`

	// (String)
	ModifiedAt *string `json:"modifiedAt,omitempty" tf:"modified_at,omitempty"`

	// (String)
	ModifiedBy *string `json:"modifiedBy,omitempty" tf:"modified_by,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (List of Map of String)
	Prompts []map[string]*string `json:"prompts,omitempty" tf:"prompts,omitempty"`

	// (String)
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// (List of Map of String)
	Tools []map[string]*string `json:"tools,omitempty" tf:"tools,omitempty"`
}

type ZeroTrustAccessAIControlsMCPServerParameters struct {

	// (String)
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-cloudflare/apis/cluster/account/v1alpha1.Account
	// +kubebuilder:validation:Optional
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// Reference to a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDRef *v1.Reference `json:"accountIdRef,omitempty" tf:"-"`

	// Selector for a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDSelector *v1.Selector `json:"accountIdSelector,omitempty" tf:"-"`

	// (String)
	// +kubebuilder:validation:Optional
	AuthCredentials *string `json:"authCredentials,omitempty" tf:"auth_credentials,omitempty"`

	// (String) Available values: "oauth", "bearer", "unauthenticated".
	// Available values: "oauth", "bearer", "unauthenticated".
	// +kubebuilder:validation:Optional
	AuthType *string `json:"authType,omitempty" tf:"auth_type,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Hostname *string `json:"hostname,omitempty" tf:"hostname,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

// ZeroTrustAccessAIControlsMCPServerSpec defines the desired state of ZeroTrustAccessAIControlsMCPServer
type ZeroTrustAccessAIControlsMCPServerSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ZeroTrustAccessAIControlsMCPServerParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ZeroTrustAccessAIControlsMCPServerInitParameters `json:"initProvider,omitempty"`
}

// ZeroTrustAccessAIControlsMCPServerStatus defines the observed state of ZeroTrustAccessAIControlsMCPServer.
type ZeroTrustAccessAIControlsMCPServerStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ZeroTrustAccessAIControlsMCPServerObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ZeroTrustAccessAIControlsMCPServer is the Schema for the ZeroTrustAccessAIControlsMCPServers API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,cloudflare}
type ZeroTrustAccessAIControlsMCPServer struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.authType) || (has(self.initProvider) && has(self.initProvider.authType))",message="spec.forProvider.authType is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.hostname) || (has(self.initProvider) && has(self.initProvider.hostname))",message="spec.forProvider.hostname is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   ZeroTrustAccessAIControlsMCPServerSpec   `json:"spec"`
	Status ZeroTrustAccessAIControlsMCPServerStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ZeroTrustAccessAIControlsMCPServerList contains a list of ZeroTrustAccessAIControlsMCPServers
type ZeroTrustAccessAIControlsMCPServerList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ZeroTrustAccessAIControlsMCPServer `json:"items"`
}

// Repository type metadata.
var (
	ZeroTrustAccessAIControlsMCPServer_Kind             = "ZeroTrustAccessAIControlsMCPServer"
	ZeroTrustAccessAIControlsMCPServer_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ZeroTrustAccessAIControlsMCPServer_Kind}.String()
	ZeroTrustAccessAIControlsMCPServer_KindAPIVersion   = ZeroTrustAccessAIControlsMCPServer_Kind + "." + CRDGroupVersion.String()
	ZeroTrustAccessAIControlsMCPServer_GroupVersionKind = CRDGroupVersion.WithKind(ZeroTrustAccessAIControlsMCPServer_Kind)
)

func init() {
	SchemeBuilder.Register(&ZeroTrustAccessAIControlsMCPServer{}, &ZeroTrustAccessAIControlsMCPServerList{})
}
