// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type AccountDNSSettingsInternalViewInitParameters struct {

	// (String) Identifier.
	// Identifier.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-cloudflare/apis/namespaced/account/v1alpha1.Account
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// Reference to a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDRef *v1.NamespacedReference `json:"accountIdRef,omitempty" tf:"-"`

	// Selector for a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDSelector *v1.NamespacedSelector `json:"accountIdSelector,omitempty" tf:"-"`

	// (String) The name of the view.
	// The name of the view.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Set of String) The list of zones linked to this view.
	// The list of zones linked to this view.
	// +listType=set
	Zones []*string `json:"zones,omitempty" tf:"zones,omitempty"`
}

type AccountDNSSettingsInternalViewObservation struct {

	// (String) Identifier.
	// Identifier.
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// (String) When the view was created.
	// When the view was created.
	CreatedTime *string `json:"createdTime,omitempty" tf:"created_time,omitempty"`

	// (String) Identifier.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) When the view was last modified.
	// When the view was last modified.
	ModifiedTime *string `json:"modifiedTime,omitempty" tf:"modified_time,omitempty"`

	// (String) The name of the view.
	// The name of the view.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Set of String) The list of zones linked to this view.
	// The list of zones linked to this view.
	// +listType=set
	Zones []*string `json:"zones,omitempty" tf:"zones,omitempty"`
}

type AccountDNSSettingsInternalViewParameters struct {

	// (String) Identifier.
	// Identifier.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-cloudflare/apis/namespaced/account/v1alpha1.Account
	// +kubebuilder:validation:Optional
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// Reference to a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDRef *v1.NamespacedReference `json:"accountIdRef,omitempty" tf:"-"`

	// Selector for a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDSelector *v1.NamespacedSelector `json:"accountIdSelector,omitempty" tf:"-"`

	// (String) The name of the view.
	// The name of the view.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Set of String) The list of zones linked to this view.
	// The list of zones linked to this view.
	// +kubebuilder:validation:Optional
	// +listType=set
	Zones []*string `json:"zones,omitempty" tf:"zones,omitempty"`
}

// AccountDNSSettingsInternalViewSpec defines the desired state of AccountDNSSettingsInternalView
type AccountDNSSettingsInternalViewSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            AccountDNSSettingsInternalViewParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AccountDNSSettingsInternalViewInitParameters `json:"initProvider,omitempty"`
}

// AccountDNSSettingsInternalViewStatus defines the observed state of AccountDNSSettingsInternalView.
type AccountDNSSettingsInternalViewStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        AccountDNSSettingsInternalViewObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// AccountDNSSettingsInternalView is the Schema for the AccountDNSSettingsInternalViews API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,cloudflare}
type AccountDNSSettingsInternalView struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.zones) || (has(self.initProvider) && has(self.initProvider.zones))",message="spec.forProvider.zones is a required parameter"
	Spec   AccountDNSSettingsInternalViewSpec   `json:"spec"`
	Status AccountDNSSettingsInternalViewStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AccountDNSSettingsInternalViewList contains a list of AccountDNSSettingsInternalViews
type AccountDNSSettingsInternalViewList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AccountDNSSettingsInternalView `json:"items"`
}

// Repository type metadata.
var (
	AccountDNSSettingsInternalView_Kind             = "AccountDNSSettingsInternalView"
	AccountDNSSettingsInternalView_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AccountDNSSettingsInternalView_Kind}.String()
	AccountDNSSettingsInternalView_KindAPIVersion   = AccountDNSSettingsInternalView_Kind + "." + CRDGroupVersion.String()
	AccountDNSSettingsInternalView_GroupVersionKind = CRDGroupVersion.WithKind(AccountDNSSettingsInternalView_Kind)
)

func init() {
	SchemeBuilder.Register(&AccountDNSSettingsInternalView{}, &AccountDNSSettingsInternalViewList{})
}
