// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type DNSZoneTransfersTSIGInitParameters struct {

	// (String)
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-cloudflare/apis/namespaced/account/v1alpha1.Account
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// Reference to a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDRef *v1.NamespacedReference `json:"accountIdRef,omitempty" tf:"-"`

	// Selector for a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDSelector *v1.NamespacedSelector `json:"accountIdSelector,omitempty" tf:"-"`

	// (String) TSIG algorithm.
	// TSIG algorithm.
	Algo *string `json:"algo,omitempty" tf:"algo,omitempty"`

	// (String) TSIG key name.
	// TSIG key name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String, Sensitive) TSIG secret.
	// TSIG secret.
	SecretSecretRef v1.LocalSecretKeySelector `json:"secretSecretRef" tf:"-"`
}

type DNSZoneTransfersTSIGObservation struct {

	// (String)
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// (String) TSIG algorithm.
	// TSIG algorithm.
	Algo *string `json:"algo,omitempty" tf:"algo,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) TSIG key name.
	// TSIG key name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type DNSZoneTransfersTSIGParameters struct {

	// (String)
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-cloudflare/apis/namespaced/account/v1alpha1.Account
	// +kubebuilder:validation:Optional
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// Reference to a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDRef *v1.NamespacedReference `json:"accountIdRef,omitempty" tf:"-"`

	// Selector for a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDSelector *v1.NamespacedSelector `json:"accountIdSelector,omitempty" tf:"-"`

	// (String) TSIG algorithm.
	// TSIG algorithm.
	// +kubebuilder:validation:Optional
	Algo *string `json:"algo,omitempty" tf:"algo,omitempty"`

	// (String) TSIG key name.
	// TSIG key name.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String, Sensitive) TSIG secret.
	// TSIG secret.
	// +kubebuilder:validation:Optional
	SecretSecretRef v1.LocalSecretKeySelector `json:"secretSecretRef" tf:"-"`
}

// DNSZoneTransfersTSIGSpec defines the desired state of DNSZoneTransfersTSIG
type DNSZoneTransfersTSIGSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            DNSZoneTransfersTSIGParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider DNSZoneTransfersTSIGInitParameters `json:"initProvider,omitempty"`
}

// DNSZoneTransfersTSIGStatus defines the observed state of DNSZoneTransfersTSIG.
type DNSZoneTransfersTSIGStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        DNSZoneTransfersTSIGObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// DNSZoneTransfersTSIG is the Schema for the DNSZoneTransfersTSIGs API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,cloudflare}
type DNSZoneTransfersTSIG struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.algo) || (has(self.initProvider) && has(self.initProvider.algo))",message="spec.forProvider.algo is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.secretSecretRef)",message="spec.forProvider.secretSecretRef is a required parameter"
	Spec   DNSZoneTransfersTSIGSpec   `json:"spec"`
	Status DNSZoneTransfersTSIGStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DNSZoneTransfersTSIGList contains a list of DNSZoneTransfersTSIGs
type DNSZoneTransfersTSIGList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DNSZoneTransfersTSIG `json:"items"`
}

// Repository type metadata.
var (
	DNSZoneTransfersTSIG_Kind             = "DNSZoneTransfersTSIG"
	DNSZoneTransfersTSIG_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: DNSZoneTransfersTSIG_Kind}.String()
	DNSZoneTransfersTSIG_KindAPIVersion   = DNSZoneTransfersTSIG_Kind + "." + CRDGroupVersion.String()
	DNSZoneTransfersTSIG_GroupVersionKind = CRDGroupVersion.WithKind(DNSZoneTransfersTSIG_Kind)
)

func init() {
	SchemeBuilder.Register(&DNSZoneTransfersTSIG{}, &DNSZoneTransfersTSIGList{})
}
