apiVersion: email.cloudflare.m.cloudflare.com/v1alpha1
kind: EmailSecurityImpersonationRegistry
metadata:
  annotations:
    meta.upbound.io/example-id: email/v1alpha1/emailsecurityimpersonationregistry
  labels:
    testing.upbound.io/example-name: example_email_security_impersonation_registry
  name: example-email-security-impersonation-registry
  namespace: crossplane-system
spec:
  forProvider:
    accountIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    email: email
    isEmailRegex: true
    name: name
