// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type ZeroTrustGatewayProxyEndpointInitParameters struct {

	// (String)
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-cloudflare/apis/namespaced/account/v1alpha1.Account
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// Reference to a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDRef *v1.NamespacedReference `json:"accountIdRef,omitempty" tf:"-"`

	// Selector for a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDSelector *v1.NamespacedSelector `json:"accountIdSelector,omitempty" tf:"-"`

	// (List of String) Specify the list of CIDRs to restrict ingress connections.
	// Specify the list of CIDRs to restrict ingress connections.
	Ips []*string `json:"ips,omitempty" tf:"ips,omitempty"`

	// (String) The proxy endpoint kind
	// Available values: "ip", "identity".
	// The proxy endpoint kind
	// Available values: "ip", "identity".
	Kind *string `json:"kind,omitempty" tf:"kind,omitempty"`

	// (String) Specify the name of the proxy endpoint.
	// Specify the name of the proxy endpoint.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type ZeroTrustGatewayProxyEndpointObservation struct {

	// (String)
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// (String)
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (List of String) Specify the list of CIDRs to restrict ingress connections.
	// Specify the list of CIDRs to restrict ingress connections.
	Ips []*string `json:"ips,omitempty" tf:"ips,omitempty"`

	// (String) The proxy endpoint kind
	// Available values: "ip", "identity".
	// The proxy endpoint kind
	// Available values: "ip", "identity".
	Kind *string `json:"kind,omitempty" tf:"kind,omitempty"`

	// (String) Specify the name of the proxy endpoint.
	// Specify the name of the proxy endpoint.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Specify the subdomain to use as the destination in the proxy client.
	// Specify the subdomain to use as the destination in the proxy client.
	Subdomain *string `json:"subdomain,omitempty" tf:"subdomain,omitempty"`

	// (String)
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`
}

type ZeroTrustGatewayProxyEndpointParameters struct {

	// (String)
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-cloudflare/apis/namespaced/account/v1alpha1.Account
	// +kubebuilder:validation:Optional
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// Reference to a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDRef *v1.NamespacedReference `json:"accountIdRef,omitempty" tf:"-"`

	// Selector for a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDSelector *v1.NamespacedSelector `json:"accountIdSelector,omitempty" tf:"-"`

	// (List of String) Specify the list of CIDRs to restrict ingress connections.
	// Specify the list of CIDRs to restrict ingress connections.
	// +kubebuilder:validation:Optional
	Ips []*string `json:"ips,omitempty" tf:"ips,omitempty"`

	// (String) The proxy endpoint kind
	// Available values: "ip", "identity".
	// The proxy endpoint kind
	// Available values: "ip", "identity".
	// +kubebuilder:validation:Optional
	Kind *string `json:"kind,omitempty" tf:"kind,omitempty"`

	// (String) Specify the name of the proxy endpoint.
	// Specify the name of the proxy endpoint.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

// ZeroTrustGatewayProxyEndpointSpec defines the desired state of ZeroTrustGatewayProxyEndpoint
type ZeroTrustGatewayProxyEndpointSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ZeroTrustGatewayProxyEndpointParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ZeroTrustGatewayProxyEndpointInitParameters `json:"initProvider,omitempty"`
}

// ZeroTrustGatewayProxyEndpointStatus defines the observed state of ZeroTrustGatewayProxyEndpoint.
type ZeroTrustGatewayProxyEndpointStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ZeroTrustGatewayProxyEndpointObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ZeroTrustGatewayProxyEndpoint is the Schema for the ZeroTrustGatewayProxyEndpoints API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,cloudflare}
type ZeroTrustGatewayProxyEndpoint struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   ZeroTrustGatewayProxyEndpointSpec   `json:"spec"`
	Status ZeroTrustGatewayProxyEndpointStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ZeroTrustGatewayProxyEndpointList contains a list of ZeroTrustGatewayProxyEndpoints
type ZeroTrustGatewayProxyEndpointList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ZeroTrustGatewayProxyEndpoint `json:"items"`
}

// Repository type metadata.
var (
	ZeroTrustGatewayProxyEndpoint_Kind             = "ZeroTrustGatewayProxyEndpoint"
	ZeroTrustGatewayProxyEndpoint_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ZeroTrustGatewayProxyEndpoint_Kind}.String()
	ZeroTrustGatewayProxyEndpoint_KindAPIVersion   = ZeroTrustGatewayProxyEndpoint_Kind + "." + CRDGroupVersion.String()
	ZeroTrustGatewayProxyEndpoint_GroupVersionKind = CRDGroupVersion.WithKind(ZeroTrustGatewayProxyEndpoint_Kind)
)

func init() {
	SchemeBuilder.Register(&ZeroTrustGatewayProxyEndpoint{}, &ZeroTrustGatewayProxyEndpointList{})
}
