// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type ZeroTrustDeviceDefaultProfileExcludeInitParameters struct {

	// (String) The address in CIDR format to exclude from the tunnel. If address is present, host must not be present.
	// The address in CIDR format to exclude from the tunnel. If `address` is present, `host` must not be present.
	Address *string `json:"address,omitempty" tf:"address,omitempty"`

	// (String) A description of the Split Tunnel item, displayed in the client UI.
	// A description of the Split Tunnel item, displayed in the client UI.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The domain name to exclude from the tunnel. If host is present, address must not be present.
	// The domain name to exclude from the tunnel. If `host` is present, `address` must not be present.
	Host *string `json:"host,omitempty" tf:"host,omitempty"`
}

type ZeroTrustDeviceDefaultProfileExcludeObservation struct {

	// (String) The address in CIDR format to exclude from the tunnel. If address is present, host must not be present.
	// The address in CIDR format to exclude from the tunnel. If `address` is present, `host` must not be present.
	Address *string `json:"address,omitempty" tf:"address,omitempty"`

	// (String) A description of the Split Tunnel item, displayed in the client UI.
	// A description of the Split Tunnel item, displayed in the client UI.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The domain name to exclude from the tunnel. If host is present, address must not be present.
	// The domain name to exclude from the tunnel. If `host` is present, `address` must not be present.
	Host *string `json:"host,omitempty" tf:"host,omitempty"`
}

type ZeroTrustDeviceDefaultProfileExcludeParameters struct {

	// (String) The address in CIDR format to exclude from the tunnel. If address is present, host must not be present.
	// The address in CIDR format to exclude from the tunnel. If `address` is present, `host` must not be present.
	// +kubebuilder:validation:Optional
	Address *string `json:"address,omitempty" tf:"address,omitempty"`

	// (String) A description of the Split Tunnel item, displayed in the client UI.
	// A description of the Split Tunnel item, displayed in the client UI.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The domain name to exclude from the tunnel. If host is present, address must not be present.
	// The domain name to exclude from the tunnel. If `host` is present, `address` must not be present.
	// +kubebuilder:validation:Optional
	Host *string `json:"host,omitempty" tf:"host,omitempty"`
}

type ZeroTrustDeviceDefaultProfileFallbackDomainsInitParameters struct {
}

type ZeroTrustDeviceDefaultProfileFallbackDomainsObservation struct {

	// (List of String) A list of IP addresses to handle domain resolution.
	// A list of IP addresses to handle domain resolution.
	DNSServer []*string `json:"dnsServer,omitempty" tf:"dns_server,omitempty"`

	// (String) A description of the Split Tunnel item, displayed in the client UI.
	// A description of the fallback domain, displayed in the client UI.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The domain suffix to match when resolving locally.
	// The domain suffix to match when resolving locally.
	Suffix *string `json:"suffix,omitempty" tf:"suffix,omitempty"`
}

type ZeroTrustDeviceDefaultProfileFallbackDomainsParameters struct {
}

type ZeroTrustDeviceDefaultProfileIncludeInitParameters struct {

	// (String) The address in CIDR format to exclude from the tunnel. If address is present, host must not be present.
	// The address in CIDR format to include in the tunnel. If `address` is present, `host` must not be present.
	Address *string `json:"address,omitempty" tf:"address,omitempty"`

	// (String) A description of the Split Tunnel item, displayed in the client UI.
	// A description of the Split Tunnel item, displayed in the client UI.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The domain name to exclude from the tunnel. If host is present, address must not be present.
	// The domain name to include in the tunnel. If `host` is present, `address` must not be present.
	Host *string `json:"host,omitempty" tf:"host,omitempty"`
}

type ZeroTrustDeviceDefaultProfileIncludeObservation struct {

	// (String) The address in CIDR format to exclude from the tunnel. If address is present, host must not be present.
	// The address in CIDR format to include in the tunnel. If `address` is present, `host` must not be present.
	Address *string `json:"address,omitempty" tf:"address,omitempty"`

	// (String) A description of the Split Tunnel item, displayed in the client UI.
	// A description of the Split Tunnel item, displayed in the client UI.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The domain name to exclude from the tunnel. If host is present, address must not be present.
	// The domain name to include in the tunnel. If `host` is present, `address` must not be present.
	Host *string `json:"host,omitempty" tf:"host,omitempty"`
}

type ZeroTrustDeviceDefaultProfileIncludeParameters struct {

	// (String) The address in CIDR format to exclude from the tunnel. If address is present, host must not be present.
	// The address in CIDR format to include in the tunnel. If `address` is present, `host` must not be present.
	// +kubebuilder:validation:Optional
	Address *string `json:"address,omitempty" tf:"address,omitempty"`

	// (String) A description of the Split Tunnel item, displayed in the client UI.
	// A description of the Split Tunnel item, displayed in the client UI.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The domain name to exclude from the tunnel. If host is present, address must not be present.
	// The domain name to include in the tunnel. If `host` is present, `address` must not be present.
	// +kubebuilder:validation:Optional
	Host *string `json:"host,omitempty" tf:"host,omitempty"`
}

type ZeroTrustDeviceDefaultProfileInitParameters struct {

	// (String)
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-cloudflare/apis/namespaced/account/v1alpha1.Account
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// Reference to a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDRef *v1.NamespacedReference `json:"accountIdRef,omitempty" tf:"-"`

	// Selector for a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDSelector *v1.NamespacedSelector `json:"accountIdSelector,omitempty" tf:"-"`

	// (Boolean) Whether to allow the user to switch WARP between modes.
	// Whether to allow the user to switch WARP between modes.
	AllowModeSwitch *bool `json:"allowModeSwitch,omitempty" tf:"allow_mode_switch,omitempty"`

	// (Boolean) Whether to receive update notifications when a new version of the client is available.
	// Whether to receive update notifications when a new version of the client is available.
	AllowUpdates *bool `json:"allowUpdates,omitempty" tf:"allow_updates,omitempty"`

	// (Boolean) Whether to allow devices to leave the organization.
	// Whether to allow devices to leave the organization.
	AllowedToLeave *bool `json:"allowedToLeave,omitempty" tf:"allowed_to_leave,omitempty"`

	// (Number) The amount of time in seconds to reconnect after having been disabled.
	// The amount of time in seconds to reconnect after having been disabled.
	AutoConnect *float64 `json:"autoConnect,omitempty" tf:"auto_connect,omitempty"`

	// (Number) Turn on the captive portal after the specified amount of time.
	// Turn on the captive portal after the specified amount of time.
	CaptivePortal *float64 `json:"captivePortal,omitempty" tf:"captive_portal,omitempty"`

	// (Boolean) If the dns_server field of a fallback domain is not present, the client will fall back to a best guess of the default/system DNS resolvers unless this policy option is set to true.
	// If the `dns_server` field of a fallback domain is not present, the client will fall back to a best guess of the default/system DNS resolvers unless this policy option is set to `true`.
	DisableAutoFallback *bool `json:"disableAutoFallback,omitempty" tf:"disable_auto_fallback,omitempty"`

	// (Attributes List) List of routes excluded in the WARP client's tunnel. Both 'exclude' and 'include' cannot be set in the same request. (see below for nested schema)
	Exclude []ZeroTrustDeviceDefaultProfileExcludeInitParameters `json:"exclude,omitempty" tf:"exclude,omitempty"`

	// (Boolean) Whether to add Microsoft IPs to Split Tunnel exclusions.
	// Whether to add Microsoft IPs to Split Tunnel exclusions.
	ExcludeOfficeIps *bool `json:"excludeOfficeIps,omitempty" tf:"exclude_office_ips,omitempty"`

	// (Attributes List) List of routes included in the WARP client's tunnel. Both 'exclude' and 'include' cannot be set in the same request. (see below for nested schema)
	Include []ZeroTrustDeviceDefaultProfileIncludeInitParameters `json:"include,omitempty" tf:"include,omitempty"`

	// (Number) The amount of time in minutes a user is allowed access to their LAN. A value of 0 will allow LAN access until the next WARP reconnection, such as a reboot or a laptop waking from sleep. Note that this field is omitted from the response if null or unset.
	// The amount of time in minutes a user is allowed access to their LAN. A value of 0 will allow LAN access until the next WARP reconnection, such as a reboot or a laptop waking from sleep. Note that this field is omitted from the response if null or unset.
	LanAllowMinutes *float64 `json:"lanAllowMinutes,omitempty" tf:"lan_allow_minutes,omitempty"`

	// (Number) The size of the subnet for the local access network. Note that this field is omitted from the response if null or unset.
	// The size of the subnet for the local access network. Note that this field is omitted from the response if null or unset.
	LanAllowSubnetSize *float64 `json:"lanAllowSubnetSize,omitempty" tf:"lan_allow_subnet_size,omitempty"`

	// premises DNS server.
	// Determines if the operating system will register WARP's local interface IP with your on-premises DNS server.
	RegisterInterfaceIPWithDNS *bool `json:"registerInterfaceIpWithDns,omitempty" tf:"register_interface_ip_with_dns,omitempty"`

	// (Boolean) Determines whether the WARP client indicates to SCCM that it is inside a VPN boundary. (Windows only).
	// Determines whether the WARP client indicates to SCCM that it is inside a VPN boundary. (Windows only).
	SccmVPNBoundarySupport *bool `json:"sccmVpnBoundarySupport,omitempty" tf:"sccm_vpn_boundary_support,omitempty"`

	// (Attributes) (see below for nested schema)
	ServiceModeV2 *ZeroTrustDeviceDefaultProfileServiceModeV2InitParameters `json:"serviceModeV2,omitempty" tf:"service_mode_v2,omitempty"`

	// (String) The URL to launch when the Send Feedback button is clicked.
	// The URL to launch when the Send Feedback button is clicked.
	SupportURL *string `json:"supportUrl,omitempty" tf:"support_url,omitempty"`

	// (Boolean) Whether to allow the user to turn off the WARP switch and disconnect the client.
	// Whether to allow the user to turn off the WARP switch and disconnect the client.
	SwitchLocked *bool `json:"switchLocked,omitempty" tf:"switch_locked,omitempty"`

	// (String) Determines which tunnel protocol to use.
	// Determines which tunnel protocol to use.
	TunnelProtocol *string `json:"tunnelProtocol,omitempty" tf:"tunnel_protocol,omitempty"`
}

type ZeroTrustDeviceDefaultProfileObservation struct {

	// (String)
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// (Boolean) Whether to allow the user to switch WARP between modes.
	// Whether to allow the user to switch WARP between modes.
	AllowModeSwitch *bool `json:"allowModeSwitch,omitempty" tf:"allow_mode_switch,omitempty"`

	// (Boolean) Whether to receive update notifications when a new version of the client is available.
	// Whether to receive update notifications when a new version of the client is available.
	AllowUpdates *bool `json:"allowUpdates,omitempty" tf:"allow_updates,omitempty"`

	// (Boolean) Whether to allow devices to leave the organization.
	// Whether to allow devices to leave the organization.
	AllowedToLeave *bool `json:"allowedToLeave,omitempty" tf:"allowed_to_leave,omitempty"`

	// (Number) The amount of time in seconds to reconnect after having been disabled.
	// The amount of time in seconds to reconnect after having been disabled.
	AutoConnect *float64 `json:"autoConnect,omitempty" tf:"auto_connect,omitempty"`

	// (Number) Turn on the captive portal after the specified amount of time.
	// Turn on the captive portal after the specified amount of time.
	CaptivePortal *float64 `json:"captivePortal,omitempty" tf:"captive_portal,omitempty"`

	// (Boolean) Whether the policy will be applied to matching devices.
	// Whether the policy will be applied to matching devices.
	Default *bool `json:"default,omitempty" tf:"default,omitempty"`

	// (Boolean) If the dns_server field of a fallback domain is not present, the client will fall back to a best guess of the default/system DNS resolvers unless this policy option is set to true.
	// If the `dns_server` field of a fallback domain is not present, the client will fall back to a best guess of the default/system DNS resolvers unless this policy option is set to `true`.
	DisableAutoFallback *bool `json:"disableAutoFallback,omitempty" tf:"disable_auto_fallback,omitempty"`

	// (Boolean) Whether the policy will be applied to matching devices.
	// Whether the policy will be applied to matching devices.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Attributes List) List of routes excluded in the WARP client's tunnel. Both 'exclude' and 'include' cannot be set in the same request. (see below for nested schema)
	Exclude []ZeroTrustDeviceDefaultProfileExcludeObservation `json:"exclude,omitempty" tf:"exclude,omitempty"`

	// (Boolean) Whether to add Microsoft IPs to Split Tunnel exclusions.
	// Whether to add Microsoft IPs to Split Tunnel exclusions.
	ExcludeOfficeIps *bool `json:"excludeOfficeIps,omitempty" tf:"exclude_office_ips,omitempty"`

	// (Attributes List) (see below for nested schema)
	FallbackDomains []ZeroTrustDeviceDefaultProfileFallbackDomainsObservation `json:"fallbackDomains,omitempty" tf:"fallback_domains,omitempty"`

	// (String)
	GatewayUniqueID *string `json:"gatewayUniqueId,omitempty" tf:"gateway_unique_id,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Attributes List) List of routes included in the WARP client's tunnel. Both 'exclude' and 'include' cannot be set in the same request. (see below for nested schema)
	Include []ZeroTrustDeviceDefaultProfileIncludeObservation `json:"include,omitempty" tf:"include,omitempty"`

	// (Number) The amount of time in minutes a user is allowed access to their LAN. A value of 0 will allow LAN access until the next WARP reconnection, such as a reboot or a laptop waking from sleep. Note that this field is omitted from the response if null or unset.
	// The amount of time in minutes a user is allowed access to their LAN. A value of 0 will allow LAN access until the next WARP reconnection, such as a reboot or a laptop waking from sleep. Note that this field is omitted from the response if null or unset.
	LanAllowMinutes *float64 `json:"lanAllowMinutes,omitempty" tf:"lan_allow_minutes,omitempty"`

	// (Number) The size of the subnet for the local access network. Note that this field is omitted from the response if null or unset.
	// The size of the subnet for the local access network. Note that this field is omitted from the response if null or unset.
	LanAllowSubnetSize *float64 `json:"lanAllowSubnetSize,omitempty" tf:"lan_allow_subnet_size,omitempty"`

	// premises DNS server.
	// Determines if the operating system will register WARP's local interface IP with your on-premises DNS server.
	RegisterInterfaceIPWithDNS *bool `json:"registerInterfaceIpWithDns,omitempty" tf:"register_interface_ip_with_dns,omitempty"`

	// (Boolean) Determines whether the WARP client indicates to SCCM that it is inside a VPN boundary. (Windows only).
	// Determines whether the WARP client indicates to SCCM that it is inside a VPN boundary. (Windows only).
	SccmVPNBoundarySupport *bool `json:"sccmVpnBoundarySupport,omitempty" tf:"sccm_vpn_boundary_support,omitempty"`

	// (Attributes) (see below for nested schema)
	ServiceModeV2 *ZeroTrustDeviceDefaultProfileServiceModeV2Observation `json:"serviceModeV2,omitempty" tf:"service_mode_v2,omitempty"`

	// (String) The URL to launch when the Send Feedback button is clicked.
	// The URL to launch when the Send Feedback button is clicked.
	SupportURL *string `json:"supportUrl,omitempty" tf:"support_url,omitempty"`

	// (Boolean) Whether to allow the user to turn off the WARP switch and disconnect the client.
	// Whether to allow the user to turn off the WARP switch and disconnect the client.
	SwitchLocked *bool `json:"switchLocked,omitempty" tf:"switch_locked,omitempty"`

	// (String) Determines which tunnel protocol to use.
	// Determines which tunnel protocol to use.
	TunnelProtocol *string `json:"tunnelProtocol,omitempty" tf:"tunnel_protocol,omitempty"`
}

type ZeroTrustDeviceDefaultProfileParameters struct {

	// (String)
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-cloudflare/apis/namespaced/account/v1alpha1.Account
	// +kubebuilder:validation:Optional
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// Reference to a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDRef *v1.NamespacedReference `json:"accountIdRef,omitempty" tf:"-"`

	// Selector for a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDSelector *v1.NamespacedSelector `json:"accountIdSelector,omitempty" tf:"-"`

	// (Boolean) Whether to allow the user to switch WARP between modes.
	// Whether to allow the user to switch WARP between modes.
	// +kubebuilder:validation:Optional
	AllowModeSwitch *bool `json:"allowModeSwitch,omitempty" tf:"allow_mode_switch,omitempty"`

	// (Boolean) Whether to receive update notifications when a new version of the client is available.
	// Whether to receive update notifications when a new version of the client is available.
	// +kubebuilder:validation:Optional
	AllowUpdates *bool `json:"allowUpdates,omitempty" tf:"allow_updates,omitempty"`

	// (Boolean) Whether to allow devices to leave the organization.
	// Whether to allow devices to leave the organization.
	// +kubebuilder:validation:Optional
	AllowedToLeave *bool `json:"allowedToLeave,omitempty" tf:"allowed_to_leave,omitempty"`

	// (Number) The amount of time in seconds to reconnect after having been disabled.
	// The amount of time in seconds to reconnect after having been disabled.
	// +kubebuilder:validation:Optional
	AutoConnect *float64 `json:"autoConnect,omitempty" tf:"auto_connect,omitempty"`

	// (Number) Turn on the captive portal after the specified amount of time.
	// Turn on the captive portal after the specified amount of time.
	// +kubebuilder:validation:Optional
	CaptivePortal *float64 `json:"captivePortal,omitempty" tf:"captive_portal,omitempty"`

	// (Boolean) If the dns_server field of a fallback domain is not present, the client will fall back to a best guess of the default/system DNS resolvers unless this policy option is set to true.
	// If the `dns_server` field of a fallback domain is not present, the client will fall back to a best guess of the default/system DNS resolvers unless this policy option is set to `true`.
	// +kubebuilder:validation:Optional
	DisableAutoFallback *bool `json:"disableAutoFallback,omitempty" tf:"disable_auto_fallback,omitempty"`

	// (Attributes List) List of routes excluded in the WARP client's tunnel. Both 'exclude' and 'include' cannot be set in the same request. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Exclude []ZeroTrustDeviceDefaultProfileExcludeParameters `json:"exclude,omitempty" tf:"exclude,omitempty"`

	// (Boolean) Whether to add Microsoft IPs to Split Tunnel exclusions.
	// Whether to add Microsoft IPs to Split Tunnel exclusions.
	// +kubebuilder:validation:Optional
	ExcludeOfficeIps *bool `json:"excludeOfficeIps,omitempty" tf:"exclude_office_ips,omitempty"`

	// (Attributes List) List of routes included in the WARP client's tunnel. Both 'exclude' and 'include' cannot be set in the same request. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Include []ZeroTrustDeviceDefaultProfileIncludeParameters `json:"include,omitempty" tf:"include,omitempty"`

	// (Number) The amount of time in minutes a user is allowed access to their LAN. A value of 0 will allow LAN access until the next WARP reconnection, such as a reboot or a laptop waking from sleep. Note that this field is omitted from the response if null or unset.
	// The amount of time in minutes a user is allowed access to their LAN. A value of 0 will allow LAN access until the next WARP reconnection, such as a reboot or a laptop waking from sleep. Note that this field is omitted from the response if null or unset.
	// +kubebuilder:validation:Optional
	LanAllowMinutes *float64 `json:"lanAllowMinutes,omitempty" tf:"lan_allow_minutes,omitempty"`

	// (Number) The size of the subnet for the local access network. Note that this field is omitted from the response if null or unset.
	// The size of the subnet for the local access network. Note that this field is omitted from the response if null or unset.
	// +kubebuilder:validation:Optional
	LanAllowSubnetSize *float64 `json:"lanAllowSubnetSize,omitempty" tf:"lan_allow_subnet_size,omitempty"`

	// premises DNS server.
	// Determines if the operating system will register WARP's local interface IP with your on-premises DNS server.
	// +kubebuilder:validation:Optional
	RegisterInterfaceIPWithDNS *bool `json:"registerInterfaceIpWithDns,omitempty" tf:"register_interface_ip_with_dns,omitempty"`

	// (Boolean) Determines whether the WARP client indicates to SCCM that it is inside a VPN boundary. (Windows only).
	// Determines whether the WARP client indicates to SCCM that it is inside a VPN boundary. (Windows only).
	// +kubebuilder:validation:Optional
	SccmVPNBoundarySupport *bool `json:"sccmVpnBoundarySupport,omitempty" tf:"sccm_vpn_boundary_support,omitempty"`

	// (Attributes) (see below for nested schema)
	// +kubebuilder:validation:Optional
	ServiceModeV2 *ZeroTrustDeviceDefaultProfileServiceModeV2Parameters `json:"serviceModeV2,omitempty" tf:"service_mode_v2,omitempty"`

	// (String) The URL to launch when the Send Feedback button is clicked.
	// The URL to launch when the Send Feedback button is clicked.
	// +kubebuilder:validation:Optional
	SupportURL *string `json:"supportUrl,omitempty" tf:"support_url,omitempty"`

	// (Boolean) Whether to allow the user to turn off the WARP switch and disconnect the client.
	// Whether to allow the user to turn off the WARP switch and disconnect the client.
	// +kubebuilder:validation:Optional
	SwitchLocked *bool `json:"switchLocked,omitempty" tf:"switch_locked,omitempty"`

	// (String) Determines which tunnel protocol to use.
	// Determines which tunnel protocol to use.
	// +kubebuilder:validation:Optional
	TunnelProtocol *string `json:"tunnelProtocol,omitempty" tf:"tunnel_protocol,omitempty"`
}

type ZeroTrustDeviceDefaultProfileServiceModeV2InitParameters struct {

	// (String) The mode to run the WARP client under.
	// The mode to run the WARP client under.
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`

	// (Number) The port number when used with proxy mode.
	// The port number when used with proxy mode.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`
}

type ZeroTrustDeviceDefaultProfileServiceModeV2Observation struct {

	// (String) The mode to run the WARP client under.
	// The mode to run the WARP client under.
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`

	// (Number) The port number when used with proxy mode.
	// The port number when used with proxy mode.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`
}

type ZeroTrustDeviceDefaultProfileServiceModeV2Parameters struct {

	// (String) The mode to run the WARP client under.
	// The mode to run the WARP client under.
	// +kubebuilder:validation:Optional
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`

	// (Number) The port number when used with proxy mode.
	// The port number when used with proxy mode.
	// +kubebuilder:validation:Optional
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`
}

// ZeroTrustDeviceDefaultProfileSpec defines the desired state of ZeroTrustDeviceDefaultProfile
type ZeroTrustDeviceDefaultProfileSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ZeroTrustDeviceDefaultProfileParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ZeroTrustDeviceDefaultProfileInitParameters `json:"initProvider,omitempty"`
}

// ZeroTrustDeviceDefaultProfileStatus defines the observed state of ZeroTrustDeviceDefaultProfile.
type ZeroTrustDeviceDefaultProfileStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ZeroTrustDeviceDefaultProfileObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ZeroTrustDeviceDefaultProfile is the Schema for the ZeroTrustDeviceDefaultProfiles API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,cloudflare}
type ZeroTrustDeviceDefaultProfile struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ZeroTrustDeviceDefaultProfileSpec   `json:"spec"`
	Status            ZeroTrustDeviceDefaultProfileStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ZeroTrustDeviceDefaultProfileList contains a list of ZeroTrustDeviceDefaultProfiles
type ZeroTrustDeviceDefaultProfileList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ZeroTrustDeviceDefaultProfile `json:"items"`
}

// Repository type metadata.
var (
	ZeroTrustDeviceDefaultProfile_Kind             = "ZeroTrustDeviceDefaultProfile"
	ZeroTrustDeviceDefaultProfile_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ZeroTrustDeviceDefaultProfile_Kind}.String()
	ZeroTrustDeviceDefaultProfile_KindAPIVersion   = ZeroTrustDeviceDefaultProfile_Kind + "." + CRDGroupVersion.String()
	ZeroTrustDeviceDefaultProfile_GroupVersionKind = CRDGroupVersion.WithKind(ZeroTrustDeviceDefaultProfile_Kind)
)

func init() {
	SchemeBuilder.Register(&ZeroTrustDeviceDefaultProfile{}, &ZeroTrustDeviceDefaultProfileList{})
}
