// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type ZeroTrustDLPIntegrationEntryConfidenceInitParameters struct {
}

type ZeroTrustDLPIntegrationEntryConfidenceObservation struct {

	// (Boolean) Indicates whether this entry has AI remote service validation.
	// Indicates whether this entry has AI remote service validation.
	AIContextAvailable *bool `json:"aiContextAvailable,omitempty" tf:"ai_context_available,omitempty"`

	// (Boolean) Indicates whether this entry has any form of validation that is not an AI remote service.
	// Indicates whether this entry has any form of validation that is not an AI remote service.
	Available *bool `json:"available,omitempty" tf:"available,omitempty"`
}

type ZeroTrustDLPIntegrationEntryConfidenceParameters struct {
}

type ZeroTrustDLPIntegrationEntryInitParameters struct {

	// (String)
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-cloudflare/apis/namespaced/account/v1alpha1.Account
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// Reference to a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDRef *v1.NamespacedReference `json:"accountIdRef,omitempty" tf:"-"`

	// Selector for a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDSelector *v1.NamespacedSelector `json:"accountIdSelector,omitempty" tf:"-"`

	// (Boolean)
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String)
	EntryID *string `json:"entryId,omitempty" tf:"entry_id,omitempty"`

	// (String) This field is not used as the owning profile.
	// For predefined entries it is already set to a predefined profile.
	// This field is not used as the owning profile.
	// For predefined entries it is already set to a predefined profile.
	ProfileID *string `json:"profileId,omitempty" tf:"profile_id,omitempty"`
}

type ZeroTrustDLPIntegrationEntryObservation struct {

	// (String)
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// sensitive manner
	// Cannot be set to false if secret is true
	// Only applies to custom word lists.
	// Determines if the words should be matched in a case-sensitive manner
	// Cannot be set to false if secret is true
	CaseSensitive *bool `json:"caseSensitive,omitempty" tf:"case_sensitive,omitempty"`

	// (Attributes) (see below for nested schema)
	Confidence *ZeroTrustDLPIntegrationEntryConfidenceObservation `json:"confidence,omitempty" tf:"confidence,omitempty"`

	// (String)
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// (Boolean)
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String)
	EntryID *string `json:"entryId,omitempty" tf:"entry_id,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Attributes) (see below for nested schema)
	Pattern *ZeroTrustDLPIntegrationEntryPatternObservation `json:"pattern,omitempty" tf:"pattern,omitempty"`

	// (String) This field is not used as the owning profile.
	// For predefined entries it is already set to a predefined profile.
	// This field is not used as the owning profile.
	// For predefined entries it is already set to a predefined profile.
	ProfileID *string `json:"profileId,omitempty" tf:"profile_id,omitempty"`

	// (Attributes List) (see below for nested schema)
	Profiles []ZeroTrustDLPIntegrationEntryProfilesObservation `json:"profiles,omitempty" tf:"profiles,omitempty"`

	// (Boolean)
	Secret *bool `json:"secret,omitempty" tf:"secret,omitempty"`

	// (String) Available values: "custom", "predefined", "integration", "exact_data", "document_fingerprint", "word_list".
	// Available values: "custom", "predefined", "integration", "exact_data", "document_fingerprint", "word_list".
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String)
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`

	// (String) Available values: "empty", "uploading", "pending", "processing", "failed", "complete".
	// Available values: "empty", "uploading", "pending", "processing", "failed", "complete".
	UploadStatus *string `json:"uploadStatus,omitempty" tf:"upload_status,omitempty"`

	// (Attributes) (see below for nested schema)
	Variant *ZeroTrustDLPIntegrationEntryVariantObservation `json:"variant,omitempty" tf:"variant,omitempty"`

	// (String)
	WordList *string `json:"wordList,omitempty" tf:"word_list,omitempty"`
}

type ZeroTrustDLPIntegrationEntryParameters struct {

	// (String)
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-cloudflare/apis/namespaced/account/v1alpha1.Account
	// +kubebuilder:validation:Optional
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// Reference to a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDRef *v1.NamespacedReference `json:"accountIdRef,omitempty" tf:"-"`

	// Selector for a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDSelector *v1.NamespacedSelector `json:"accountIdSelector,omitempty" tf:"-"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	EntryID *string `json:"entryId,omitempty" tf:"entry_id,omitempty"`

	// (String) This field is not used as the owning profile.
	// For predefined entries it is already set to a predefined profile.
	// This field is not used as the owning profile.
	// For predefined entries it is already set to a predefined profile.
	// +kubebuilder:validation:Optional
	ProfileID *string `json:"profileId,omitempty" tf:"profile_id,omitempty"`
}

type ZeroTrustDLPIntegrationEntryPatternInitParameters struct {
}

type ZeroTrustDLPIntegrationEntryPatternObservation struct {

	// (String)
	Regex *string `json:"regex,omitempty" tf:"regex,omitempty"`

	// (String, Deprecated) Available values: "luhn".
	// Available values: "luhn".
	Validation *string `json:"validation,omitempty" tf:"validation,omitempty"`
}

type ZeroTrustDLPIntegrationEntryPatternParameters struct {
}

type ZeroTrustDLPIntegrationEntryProfilesInitParameters struct {
}

type ZeroTrustDLPIntegrationEntryProfilesObservation struct {

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type ZeroTrustDLPIntegrationEntryProfilesParameters struct {
}

type ZeroTrustDLPIntegrationEntryVariantInitParameters struct {
}

type ZeroTrustDLPIntegrationEntryVariantObservation struct {

	// (String)
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Available values: "Intent", "Content".
	// Available values: "Intent", "Content".
	TopicType *string `json:"topicType,omitempty" tf:"topic_type,omitempty"`

	// (String) Available values: "custom", "predefined", "integration", "exact_data", "document_fingerprint", "word_list".
	// Available values: "PromptTopic".
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ZeroTrustDLPIntegrationEntryVariantParameters struct {
}

// ZeroTrustDLPIntegrationEntrySpec defines the desired state of ZeroTrustDLPIntegrationEntry
type ZeroTrustDLPIntegrationEntrySpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ZeroTrustDLPIntegrationEntryParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ZeroTrustDLPIntegrationEntryInitParameters `json:"initProvider,omitempty"`
}

// ZeroTrustDLPIntegrationEntryStatus defines the observed state of ZeroTrustDLPIntegrationEntry.
type ZeroTrustDLPIntegrationEntryStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ZeroTrustDLPIntegrationEntryObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ZeroTrustDLPIntegrationEntry is the Schema for the ZeroTrustDLPIntegrationEntrys API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,cloudflare}
type ZeroTrustDLPIntegrationEntry struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.enabled) || (has(self.initProvider) && has(self.initProvider.enabled))",message="spec.forProvider.enabled is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.entryId) || (has(self.initProvider) && has(self.initProvider.entryId))",message="spec.forProvider.entryId is a required parameter"
	Spec   ZeroTrustDLPIntegrationEntrySpec   `json:"spec"`
	Status ZeroTrustDLPIntegrationEntryStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ZeroTrustDLPIntegrationEntryList contains a list of ZeroTrustDLPIntegrationEntrys
type ZeroTrustDLPIntegrationEntryList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ZeroTrustDLPIntegrationEntry `json:"items"`
}

// Repository type metadata.
var (
	ZeroTrustDLPIntegrationEntry_Kind             = "ZeroTrustDLPIntegrationEntry"
	ZeroTrustDLPIntegrationEntry_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ZeroTrustDLPIntegrationEntry_Kind}.String()
	ZeroTrustDLPIntegrationEntry_KindAPIVersion   = ZeroTrustDLPIntegrationEntry_Kind + "." + CRDGroupVersion.String()
	ZeroTrustDLPIntegrationEntry_GroupVersionKind = CRDGroupVersion.WithKind(ZeroTrustDLPIntegrationEntry_Kind)
)

func init() {
	SchemeBuilder.Register(&ZeroTrustDLPIntegrationEntry{}, &ZeroTrustDLPIntegrationEntryList{})
}
