// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type WorkersForPlatformsDispatchNamespaceInitParameters struct {

	// (String) Identifier.
	// Identifier.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-cloudflare/apis/cluster/account/v1alpha1.Account
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// Reference to a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDRef *v1.Reference `json:"accountIdRef,omitempty" tf:"-"`

	// Selector for a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDSelector *v1.Selector `json:"accountIdSelector,omitempty" tf:"-"`

	// (String) The name of the dispatch namespace.
	// The name of the dispatch namespace.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type WorkersForPlatformsDispatchNamespaceObservation struct {

	// (String) Identifier.
	// Identifier.
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// (String) Identifier.
	// Identifier.
	CreatedBy *string `json:"createdBy,omitempty" tf:"created_by,omitempty"`

	// (String) When the script was created.
	// When the script was created.
	CreatedOn *string `json:"createdOn,omitempty" tf:"created_on,omitempty"`

	// (String) Name of the Workers for Platforms dispatch namespace.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Identifier.
	// Identifier.
	ModifiedBy *string `json:"modifiedBy,omitempty" tf:"modified_by,omitempty"`

	// (String) When the script was last modified.
	// When the script was last modified.
	ModifiedOn *string `json:"modifiedOn,omitempty" tf:"modified_on,omitempty"`

	// (String) The name of the dispatch namespace.
	// The name of the dispatch namespace.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) API Resource UUID tag.
	// API Resource UUID tag.
	NamespaceID *string `json:"namespaceId,omitempty" tf:"namespace_id,omitempty"`

	// (String) Name of the Workers for Platforms dispatch namespace.
	// Name of the Workers for Platforms dispatch namespace.
	NamespaceName *string `json:"namespaceName,omitempty" tf:"namespace_name,omitempty"`

	// (Number) The current number of scripts in this Dispatch Namespace.
	// The current number of scripts in this Dispatch Namespace.
	ScriptCount *float64 `json:"scriptCount,omitempty" tf:"script_count,omitempty"`

	// (Boolean) Whether the Workers in the namespace are executed in a "trusted" manner. When a Worker is trusted, it has access to the shared caches for the zone in the Cache API, and has access to the request.cf object on incoming Requests. When a Worker is untrusted, caches are not shared across the zone, and request.cf is undefined. By default, Workers in a namespace are "untrusted".
	// Whether the Workers in the namespace are executed in a "trusted" manner. When a Worker is trusted, it has access to the shared caches for the zone in the Cache API, and has access to the `request.cf` object on incoming Requests. When a Worker is untrusted, caches are not shared across the zone, and `request.cf` is undefined. By default, Workers in a namespace are "untrusted".
	TrustedWorkers *bool `json:"trustedWorkers,omitempty" tf:"trusted_workers,omitempty"`
}

type WorkersForPlatformsDispatchNamespaceParameters struct {

	// (String) Identifier.
	// Identifier.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-cloudflare/apis/cluster/account/v1alpha1.Account
	// +kubebuilder:validation:Optional
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// Reference to a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDRef *v1.Reference `json:"accountIdRef,omitempty" tf:"-"`

	// Selector for a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDSelector *v1.Selector `json:"accountIdSelector,omitempty" tf:"-"`

	// (String) The name of the dispatch namespace.
	// The name of the dispatch namespace.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

// WorkersForPlatformsDispatchNamespaceSpec defines the desired state of WorkersForPlatformsDispatchNamespace
type WorkersForPlatformsDispatchNamespaceSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     WorkersForPlatformsDispatchNamespaceParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider WorkersForPlatformsDispatchNamespaceInitParameters `json:"initProvider,omitempty"`
}

// WorkersForPlatformsDispatchNamespaceStatus defines the observed state of WorkersForPlatformsDispatchNamespace.
type WorkersForPlatformsDispatchNamespaceStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        WorkersForPlatformsDispatchNamespaceObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// WorkersForPlatformsDispatchNamespace is the Schema for the WorkersForPlatformsDispatchNamespaces API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,cloudflare}
type WorkersForPlatformsDispatchNamespace struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              WorkersForPlatformsDispatchNamespaceSpec   `json:"spec"`
	Status            WorkersForPlatformsDispatchNamespaceStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// WorkersForPlatformsDispatchNamespaceList contains a list of WorkersForPlatformsDispatchNamespaces
type WorkersForPlatformsDispatchNamespaceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []WorkersForPlatformsDispatchNamespace `json:"items"`
}

// Repository type metadata.
var (
	WorkersForPlatformsDispatchNamespace_Kind             = "WorkersForPlatformsDispatchNamespace"
	WorkersForPlatformsDispatchNamespace_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: WorkersForPlatformsDispatchNamespace_Kind}.String()
	WorkersForPlatformsDispatchNamespace_KindAPIVersion   = WorkersForPlatformsDispatchNamespace_Kind + "." + CRDGroupVersion.String()
	WorkersForPlatformsDispatchNamespace_GroupVersionKind = CRDGroupVersion.WithKind(WorkersForPlatformsDispatchNamespace_Kind)
)

func init() {
	SchemeBuilder.Register(&WorkersForPlatformsDispatchNamespace{}, &WorkersForPlatformsDispatchNamespaceList{})
}
