// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type ZeroTrustAccessMTLSCertificateInitParameters struct {

	// (String) The Account ID to use for this endpoint. Mutually exclusive with the Zone ID.
	// The Account ID to use for this endpoint. Mutually exclusive with the Zone ID.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-cloudflare/apis/namespaced/account/v1alpha1.Account
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// Reference to a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDRef *v1.NamespacedReference `json:"accountIdRef,omitempty" tf:"-"`

	// Selector for a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDSelector *v1.NamespacedSelector `json:"accountIdSelector,omitempty" tf:"-"`

	// (Set of String) The hostnames of the applications that will use this certificate.
	// The hostnames of the applications that will use this certificate.
	// +listType=set
	AssociatedHostnames []*string `json:"associatedHostnames,omitempty" tf:"associated_hostnames,omitempty"`

	// (String) The certificate content.
	// The certificate content.
	Certificate *string `json:"certificate,omitempty" tf:"certificate,omitempty"`

	// (String) The name of the certificate.
	// The name of the certificate.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The Zone ID to use for this endpoint. Mutually exclusive with the Account ID.
	// The Zone ID to use for this endpoint. Mutually exclusive with the Account ID.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-cloudflare/apis/namespaced/zone/v1alpha1.Zone
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`

	// Reference to a Zone in zone to populate zoneId.
	// +kubebuilder:validation:Optional
	ZoneIDRef *v1.NamespacedReference `json:"zoneIdRef,omitempty" tf:"-"`

	// Selector for a Zone in zone to populate zoneId.
	// +kubebuilder:validation:Optional
	ZoneIDSelector *v1.NamespacedSelector `json:"zoneIdSelector,omitempty" tf:"-"`
}

type ZeroTrustAccessMTLSCertificateObservation struct {

	// (String) The Account ID to use for this endpoint. Mutually exclusive with the Zone ID.
	// The Account ID to use for this endpoint. Mutually exclusive with the Zone ID.
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// (Set of String) The hostnames of the applications that will use this certificate.
	// The hostnames of the applications that will use this certificate.
	// +listType=set
	AssociatedHostnames []*string `json:"associatedHostnames,omitempty" tf:"associated_hostnames,omitempty"`

	// (String) The certificate content.
	// The certificate content.
	Certificate *string `json:"certificate,omitempty" tf:"certificate,omitempty"`

	// (String)
	ExpiresOn *string `json:"expiresOn,omitempty" tf:"expires_on,omitempty"`

	// (String) The MD5 fingerprint of the certificate.
	// The MD5 fingerprint of the certificate.
	Fingerprint *string `json:"fingerprint,omitempty" tf:"fingerprint,omitempty"`

	// (String) The ID of the application that will use this certificate.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The name of the certificate.
	// The name of the certificate.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The Zone ID to use for this endpoint. Mutually exclusive with the Account ID.
	// The Zone ID to use for this endpoint. Mutually exclusive with the Account ID.
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`
}

type ZeroTrustAccessMTLSCertificateParameters struct {

	// (String) The Account ID to use for this endpoint. Mutually exclusive with the Zone ID.
	// The Account ID to use for this endpoint. Mutually exclusive with the Zone ID.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-cloudflare/apis/namespaced/account/v1alpha1.Account
	// +kubebuilder:validation:Optional
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// Reference to a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDRef *v1.NamespacedReference `json:"accountIdRef,omitempty" tf:"-"`

	// Selector for a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDSelector *v1.NamespacedSelector `json:"accountIdSelector,omitempty" tf:"-"`

	// (Set of String) The hostnames of the applications that will use this certificate.
	// The hostnames of the applications that will use this certificate.
	// +kubebuilder:validation:Optional
	// +listType=set
	AssociatedHostnames []*string `json:"associatedHostnames,omitempty" tf:"associated_hostnames,omitempty"`

	// (String) The certificate content.
	// The certificate content.
	// +kubebuilder:validation:Optional
	Certificate *string `json:"certificate,omitempty" tf:"certificate,omitempty"`

	// (String) The name of the certificate.
	// The name of the certificate.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The Zone ID to use for this endpoint. Mutually exclusive with the Account ID.
	// The Zone ID to use for this endpoint. Mutually exclusive with the Account ID.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-cloudflare/apis/namespaced/zone/v1alpha1.Zone
	// +kubebuilder:validation:Optional
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`

	// Reference to a Zone in zone to populate zoneId.
	// +kubebuilder:validation:Optional
	ZoneIDRef *v1.NamespacedReference `json:"zoneIdRef,omitempty" tf:"-"`

	// Selector for a Zone in zone to populate zoneId.
	// +kubebuilder:validation:Optional
	ZoneIDSelector *v1.NamespacedSelector `json:"zoneIdSelector,omitempty" tf:"-"`
}

// ZeroTrustAccessMTLSCertificateSpec defines the desired state of ZeroTrustAccessMTLSCertificate
type ZeroTrustAccessMTLSCertificateSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ZeroTrustAccessMTLSCertificateParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ZeroTrustAccessMTLSCertificateInitParameters `json:"initProvider,omitempty"`
}

// ZeroTrustAccessMTLSCertificateStatus defines the observed state of ZeroTrustAccessMTLSCertificate.
type ZeroTrustAccessMTLSCertificateStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ZeroTrustAccessMTLSCertificateObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ZeroTrustAccessMTLSCertificate is the Schema for the ZeroTrustAccessMTLSCertificates API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,cloudflare}
type ZeroTrustAccessMTLSCertificate struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.certificate) || (has(self.initProvider) && has(self.initProvider.certificate))",message="spec.forProvider.certificate is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   ZeroTrustAccessMTLSCertificateSpec   `json:"spec"`
	Status ZeroTrustAccessMTLSCertificateStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ZeroTrustAccessMTLSCertificateList contains a list of ZeroTrustAccessMTLSCertificates
type ZeroTrustAccessMTLSCertificateList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ZeroTrustAccessMTLSCertificate `json:"items"`
}

// Repository type metadata.
var (
	ZeroTrustAccessMTLSCertificate_Kind             = "ZeroTrustAccessMTLSCertificate"
	ZeroTrustAccessMTLSCertificate_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ZeroTrustAccessMTLSCertificate_Kind}.String()
	ZeroTrustAccessMTLSCertificate_KindAPIVersion   = ZeroTrustAccessMTLSCertificate_Kind + "." + CRDGroupVersion.String()
	ZeroTrustAccessMTLSCertificate_GroupVersionKind = CRDGroupVersion.WithKind(ZeroTrustAccessMTLSCertificate_Kind)
)

func init() {
	SchemeBuilder.Register(&ZeroTrustAccessMTLSCertificate{}, &ZeroTrustAccessMTLSCertificateList{})
}
