// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type R2BucketEventNotificationInitParameters struct {

	// (String) Account ID.
	// Account ID.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-cloudflare/apis/namespaced/account/v1alpha1.Account
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// Reference to a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDRef *v1.NamespacedReference `json:"accountIdRef,omitempty" tf:"-"`

	// Selector for a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDSelector *v1.NamespacedSelector `json:"accountIdSelector,omitempty" tf:"-"`

	// (String) Name of the bucket.
	// Name of the bucket.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-cloudflare/apis/namespaced/r2/v1alpha1.R2Bucket
	BucketName *string `json:"bucketName,omitempty" tf:"bucket_name,omitempty"`

	// Reference to a R2Bucket in r2 to populate bucketName.
	// +kubebuilder:validation:Optional
	BucketNameRef *v1.NamespacedReference `json:"bucketNameRef,omitempty" tf:"-"`

	// Selector for a R2Bucket in r2 to populate bucketName.
	// +kubebuilder:validation:Optional
	BucketNameSelector *v1.NamespacedSelector `json:"bucketNameSelector,omitempty" tf:"-"`

	// (String) Jurisdiction of the bucket
	// Jurisdiction of the bucket
	Jurisdiction *string `json:"jurisdiction,omitempty" tf:"jurisdiction,omitempty"`

	// (String) Queue ID.
	// Queue ID.
	QueueID *string `json:"queueId,omitempty" tf:"queue_id,omitempty"`

	// (Attributes List) Array of rules to drive notifications. (see below for nested schema)
	Rules []R2BucketEventNotificationRulesInitParameters `json:"rules,omitempty" tf:"rules,omitempty"`
}

type R2BucketEventNotificationObservation struct {

	// (String) Account ID.
	// Account ID.
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// (String) Name of the bucket.
	// Name of the bucket.
	BucketName *string `json:"bucketName,omitempty" tf:"bucket_name,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Jurisdiction of the bucket
	// Jurisdiction of the bucket
	Jurisdiction *string `json:"jurisdiction,omitempty" tf:"jurisdiction,omitempty"`

	// (String) Queue ID.
	// Queue ID.
	QueueID *string `json:"queueId,omitempty" tf:"queue_id,omitempty"`

	// (String) Name of the queue.
	// Name of the queue.
	QueueName *string `json:"queueName,omitempty" tf:"queue_name,omitempty"`

	// (Attributes List) Array of rules to drive notifications. (see below for nested schema)
	Rules []R2BucketEventNotificationRulesObservation `json:"rules,omitempty" tf:"rules,omitempty"`
}

type R2BucketEventNotificationParameters struct {

	// (String) Account ID.
	// Account ID.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-cloudflare/apis/namespaced/account/v1alpha1.Account
	// +kubebuilder:validation:Optional
	AccountID *string `json:"accountId,omitempty" tf:"account_id,omitempty"`

	// Reference to a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDRef *v1.NamespacedReference `json:"accountIdRef,omitempty" tf:"-"`

	// Selector for a Account in account to populate accountId.
	// +kubebuilder:validation:Optional
	AccountIDSelector *v1.NamespacedSelector `json:"accountIdSelector,omitempty" tf:"-"`

	// (String) Name of the bucket.
	// Name of the bucket.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-cloudflare/apis/namespaced/r2/v1alpha1.R2Bucket
	// +kubebuilder:validation:Optional
	BucketName *string `json:"bucketName,omitempty" tf:"bucket_name,omitempty"`

	// Reference to a R2Bucket in r2 to populate bucketName.
	// +kubebuilder:validation:Optional
	BucketNameRef *v1.NamespacedReference `json:"bucketNameRef,omitempty" tf:"-"`

	// Selector for a R2Bucket in r2 to populate bucketName.
	// +kubebuilder:validation:Optional
	BucketNameSelector *v1.NamespacedSelector `json:"bucketNameSelector,omitempty" tf:"-"`

	// (String) Jurisdiction of the bucket
	// Jurisdiction of the bucket
	// +kubebuilder:validation:Optional
	Jurisdiction *string `json:"jurisdiction,omitempty" tf:"jurisdiction,omitempty"`

	// (String) Queue ID.
	// Queue ID.
	// +kubebuilder:validation:Optional
	QueueID *string `json:"queueId,omitempty" tf:"queue_id,omitempty"`

	// (Attributes List) Array of rules to drive notifications. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Rules []R2BucketEventNotificationRulesParameters `json:"rules,omitempty" tf:"rules,omitempty"`
}

type R2BucketEventNotificationRulesInitParameters struct {

	// (List of String) Array of R2 object actions that will trigger notifications.
	// Array of R2 object actions that will trigger notifications.
	Actions []*string `json:"actions,omitempty" tf:"actions,omitempty"`

	// (String) A description that can be used to identify the event notification rule after creation.
	// A description that can be used to identify the event notification rule after creation.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Notifications will be sent only for objects with this prefix.
	// Notifications will be sent only for objects with this prefix.
	Prefix *string `json:"prefix,omitempty" tf:"prefix,omitempty"`

	// (String) Notifications will be sent only for objects with this suffix.
	// Notifications will be sent only for objects with this suffix.
	Suffix *string `json:"suffix,omitempty" tf:"suffix,omitempty"`
}

type R2BucketEventNotificationRulesObservation struct {

	// (List of String) Array of R2 object actions that will trigger notifications.
	// Array of R2 object actions that will trigger notifications.
	Actions []*string `json:"actions,omitempty" tf:"actions,omitempty"`

	// (String) A description that can be used to identify the event notification rule after creation.
	// A description that can be used to identify the event notification rule after creation.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Notifications will be sent only for objects with this prefix.
	// Notifications will be sent only for objects with this prefix.
	Prefix *string `json:"prefix,omitempty" tf:"prefix,omitempty"`

	// (String) Notifications will be sent only for objects with this suffix.
	// Notifications will be sent only for objects with this suffix.
	Suffix *string `json:"suffix,omitempty" tf:"suffix,omitempty"`
}

type R2BucketEventNotificationRulesParameters struct {

	// (List of String) Array of R2 object actions that will trigger notifications.
	// Array of R2 object actions that will trigger notifications.
	// +kubebuilder:validation:Optional
	Actions []*string `json:"actions" tf:"actions,omitempty"`

	// (String) A description that can be used to identify the event notification rule after creation.
	// A description that can be used to identify the event notification rule after creation.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Notifications will be sent only for objects with this prefix.
	// Notifications will be sent only for objects with this prefix.
	// +kubebuilder:validation:Optional
	Prefix *string `json:"prefix,omitempty" tf:"prefix,omitempty"`

	// (String) Notifications will be sent only for objects with this suffix.
	// Notifications will be sent only for objects with this suffix.
	// +kubebuilder:validation:Optional
	Suffix *string `json:"suffix,omitempty" tf:"suffix,omitempty"`
}

// R2BucketEventNotificationSpec defines the desired state of R2BucketEventNotification
type R2BucketEventNotificationSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            R2BucketEventNotificationParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider R2BucketEventNotificationInitParameters `json:"initProvider,omitempty"`
}

// R2BucketEventNotificationStatus defines the observed state of R2BucketEventNotification.
type R2BucketEventNotificationStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        R2BucketEventNotificationObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// R2BucketEventNotification is the Schema for the R2BucketEventNotifications API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,cloudflare}
type R2BucketEventNotification struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.queueId) || (has(self.initProvider) && has(self.initProvider.queueId))",message="spec.forProvider.queueId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.rules) || (has(self.initProvider) && has(self.initProvider.rules))",message="spec.forProvider.rules is a required parameter"
	Spec   R2BucketEventNotificationSpec   `json:"spec"`
	Status R2BucketEventNotificationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// R2BucketEventNotificationList contains a list of R2BucketEventNotifications
type R2BucketEventNotificationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []R2BucketEventNotification `json:"items"`
}

// Repository type metadata.
var (
	R2BucketEventNotification_Kind             = "R2BucketEventNotification"
	R2BucketEventNotification_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: R2BucketEventNotification_Kind}.String()
	R2BucketEventNotification_KindAPIVersion   = R2BucketEventNotification_Kind + "." + CRDGroupVersion.String()
	R2BucketEventNotification_GroupVersionKind = CRDGroupVersion.WithKind(R2BucketEventNotification_Kind)
)

func init() {
	SchemeBuilder.Register(&R2BucketEventNotification{}, &R2BucketEventNotificationList{})
}
