// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type CredentialsInitParameters struct {

	// (Attributes List) (see below for nested schema)
	Keys []KeysInitParameters `json:"keys,omitempty" tf:"keys,omitempty"`
}

type CredentialsObservation struct {

	// (Attributes List) (see below for nested schema)
	Keys []KeysObservation `json:"keys,omitempty" tf:"keys,omitempty"`
}

type CredentialsParameters struct {

	// (Attributes List) (see below for nested schema)
	// +kubebuilder:validation:Optional
	Keys []KeysParameters `json:"keys" tf:"keys,omitempty"`
}

type KeysInitParameters struct {

	// (String) Algorithm
	// Available values: "RS256", "RS384", "RS512", "PS256", "PS384", "PS512", "ES256", "ES384".
	// Algorithm
	// Available values: "RS256", "RS384", "RS512", "PS256", "PS384", "PS512", "ES256", "ES384".
	Alg *string `json:"alg,omitempty" tf:"alg,omitempty"`

	// 256", "P-384".
	// Curve
	// Available values: "P-256", "P-384".
	Crv *string `json:"crv,omitempty" tf:"crv,omitempty"`

	// (String) RSA exponent
	// RSA exponent
	E *string `json:"e,omitempty" tf:"e,omitempty"`

	// (String) Key ID
	// Key ID
	Kid *string `json:"kid,omitempty" tf:"kid,omitempty"`

	// (String) Key Type
	// Available values: "RSA", "EC".
	// Key Type
	// Available values: "RSA", "EC".
	Kty *string `json:"kty,omitempty" tf:"kty,omitempty"`

	// (String) RSA modulus
	// RSA modulus
	N *string `json:"n,omitempty" tf:"n,omitempty"`

	// (String) X EC coordinate
	// X EC coordinate
	X *string `json:"x,omitempty" tf:"x,omitempty"`

	// (String) Y EC coordinate
	// Y EC coordinate
	Y *string `json:"y,omitempty" tf:"y,omitempty"`
}

type KeysObservation struct {

	// (String) Algorithm
	// Available values: "RS256", "RS384", "RS512", "PS256", "PS384", "PS512", "ES256", "ES384".
	// Algorithm
	// Available values: "RS256", "RS384", "RS512", "PS256", "PS384", "PS512", "ES256", "ES384".
	Alg *string `json:"alg,omitempty" tf:"alg,omitempty"`

	// 256", "P-384".
	// Curve
	// Available values: "P-256", "P-384".
	Crv *string `json:"crv,omitempty" tf:"crv,omitempty"`

	// (String) RSA exponent
	// RSA exponent
	E *string `json:"e,omitempty" tf:"e,omitempty"`

	// (String) Key ID
	// Key ID
	Kid *string `json:"kid,omitempty" tf:"kid,omitempty"`

	// (String) Key Type
	// Available values: "RSA", "EC".
	// Key Type
	// Available values: "RSA", "EC".
	Kty *string `json:"kty,omitempty" tf:"kty,omitempty"`

	// (String) RSA modulus
	// RSA modulus
	N *string `json:"n,omitempty" tf:"n,omitempty"`

	// (String) X EC coordinate
	// X EC coordinate
	X *string `json:"x,omitempty" tf:"x,omitempty"`

	// (String) Y EC coordinate
	// Y EC coordinate
	Y *string `json:"y,omitempty" tf:"y,omitempty"`
}

type KeysParameters struct {

	// (String) Algorithm
	// Available values: "RS256", "RS384", "RS512", "PS256", "PS384", "PS512", "ES256", "ES384".
	// Algorithm
	// Available values: "RS256", "RS384", "RS512", "PS256", "PS384", "PS512", "ES256", "ES384".
	// +kubebuilder:validation:Optional
	Alg *string `json:"alg" tf:"alg,omitempty"`

	// 256", "P-384".
	// Curve
	// Available values: "P-256", "P-384".
	// +kubebuilder:validation:Optional
	Crv *string `json:"crv,omitempty" tf:"crv,omitempty"`

	// (String) RSA exponent
	// RSA exponent
	// +kubebuilder:validation:Optional
	E *string `json:"e,omitempty" tf:"e,omitempty"`

	// (String) Key ID
	// Key ID
	// +kubebuilder:validation:Optional
	Kid *string `json:"kid" tf:"kid,omitempty"`

	// (String) Key Type
	// Available values: "RSA", "EC".
	// Key Type
	// Available values: "RSA", "EC".
	// +kubebuilder:validation:Optional
	Kty *string `json:"kty" tf:"kty,omitempty"`

	// (String) RSA modulus
	// RSA modulus
	// +kubebuilder:validation:Optional
	N *string `json:"n,omitempty" tf:"n,omitempty"`

	// (String) X EC coordinate
	// X EC coordinate
	// +kubebuilder:validation:Optional
	X *string `json:"x,omitempty" tf:"x,omitempty"`

	// (String) Y EC coordinate
	// Y EC coordinate
	// +kubebuilder:validation:Optional
	Y *string `json:"y,omitempty" tf:"y,omitempty"`
}

type TokenValidationConfigInitParameters struct {

	// (Attributes) (see below for nested schema)
	Credentials *CredentialsInitParameters `json:"credentials,omitempty" tf:"credentials,omitempty"`

	// (String)
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String)
	Title *string `json:"title,omitempty" tf:"title,omitempty"`

	// (List of String)
	TokenSources []*string `json:"tokenSources,omitempty" tf:"token_sources,omitempty"`

	// (String) Available values: "JWT".
	// Available values: "JWT".
	TokenType *string `json:"tokenType,omitempty" tf:"token_type,omitempty"`

	// (String) Identifier.
	// Identifier.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-cloudflare/apis/cluster/zone/v1alpha1.Zone
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`

	// Reference to a Zone in zone to populate zoneId.
	// +kubebuilder:validation:Optional
	ZoneIDRef *v1.Reference `json:"zoneIdRef,omitempty" tf:"-"`

	// Selector for a Zone in zone to populate zoneId.
	// +kubebuilder:validation:Optional
	ZoneIDSelector *v1.Selector `json:"zoneIdSelector,omitempty" tf:"-"`
}

type TokenValidationConfigObservation struct {

	// (String)
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// (Attributes) (see below for nested schema)
	Credentials *CredentialsObservation `json:"credentials,omitempty" tf:"credentials,omitempty"`

	// (String)
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) UUID.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String)
	LastUpdated *string `json:"lastUpdated,omitempty" tf:"last_updated,omitempty"`

	// (String)
	Title *string `json:"title,omitempty" tf:"title,omitempty"`

	// (List of String)
	TokenSources []*string `json:"tokenSources,omitempty" tf:"token_sources,omitempty"`

	// (String) Available values: "JWT".
	// Available values: "JWT".
	TokenType *string `json:"tokenType,omitempty" tf:"token_type,omitempty"`

	// (String) Identifier.
	// Identifier.
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`
}

type TokenValidationConfigParameters struct {

	// (Attributes) (see below for nested schema)
	// +kubebuilder:validation:Optional
	Credentials *CredentialsParameters `json:"credentials,omitempty" tf:"credentials,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Title *string `json:"title,omitempty" tf:"title,omitempty"`

	// (List of String)
	// +kubebuilder:validation:Optional
	TokenSources []*string `json:"tokenSources,omitempty" tf:"token_sources,omitempty"`

	// (String) Available values: "JWT".
	// Available values: "JWT".
	// +kubebuilder:validation:Optional
	TokenType *string `json:"tokenType,omitempty" tf:"token_type,omitempty"`

	// (String) Identifier.
	// Identifier.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-cloudflare/apis/cluster/zone/v1alpha1.Zone
	// +kubebuilder:validation:Optional
	ZoneID *string `json:"zoneId,omitempty" tf:"zone_id,omitempty"`

	// Reference to a Zone in zone to populate zoneId.
	// +kubebuilder:validation:Optional
	ZoneIDRef *v1.Reference `json:"zoneIdRef,omitempty" tf:"-"`

	// Selector for a Zone in zone to populate zoneId.
	// +kubebuilder:validation:Optional
	ZoneIDSelector *v1.Selector `json:"zoneIdSelector,omitempty" tf:"-"`
}

// TokenValidationConfigSpec defines the desired state of TokenValidationConfig
type TokenValidationConfigSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     TokenValidationConfigParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider TokenValidationConfigInitParameters `json:"initProvider,omitempty"`
}

// TokenValidationConfigStatus defines the observed state of TokenValidationConfig.
type TokenValidationConfigStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        TokenValidationConfigObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// TokenValidationConfig is the Schema for the TokenValidationConfigs API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,cloudflare}
type TokenValidationConfig struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.credentials) || (has(self.initProvider) && has(self.initProvider.credentials))",message="spec.forProvider.credentials is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.description) || (has(self.initProvider) && has(self.initProvider.description))",message="spec.forProvider.description is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.title) || (has(self.initProvider) && has(self.initProvider.title))",message="spec.forProvider.title is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.tokenSources) || (has(self.initProvider) && has(self.initProvider.tokenSources))",message="spec.forProvider.tokenSources is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.tokenType) || (has(self.initProvider) && has(self.initProvider.tokenType))",message="spec.forProvider.tokenType is a required parameter"
	Spec   TokenValidationConfigSpec   `json:"spec"`
	Status TokenValidationConfigStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// TokenValidationConfigList contains a list of TokenValidationConfigs
type TokenValidationConfigList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TokenValidationConfig `json:"items"`
}

// Repository type metadata.
var (
	TokenValidationConfig_Kind             = "TokenValidationConfig"
	TokenValidationConfig_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: TokenValidationConfig_Kind}.String()
	TokenValidationConfig_KindAPIVersion   = TokenValidationConfig_Kind + "." + CRDGroupVersion.String()
	TokenValidationConfig_GroupVersionKind = CRDGroupVersion.WithKind(TokenValidationConfig_Kind)
)

func init() {
	SchemeBuilder.Register(&TokenValidationConfig{}, &TokenValidationConfigList{})
}
