apiVersion: zone.cloudflare.m.cloudflare.com/v1alpha1
kind: ZoneSubscription
metadata:
  annotations:
    meta.upbound.io/example-id: zone/v1alpha1/zonesubscription
  labels:
    testing.upbound.io/example-name: example_zone_subscription
  name: example-zone-subscription
  namespace: crossplane-system
spec:
  forProvider:
    frequency: monthly
    ratePlan:
      id: free
      scope: zone
    zoneIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
