apiVersion: apishield.cloudflare.crossplane.io/v1alpha1
kind: APIShieldDiscoveryOperation
metadata:
  annotations:
    meta.upbound.io/example-id: apishield/v1alpha1/apishielddiscoveryoperation
  labels:
    testing.upbound.io/example-name: example_api_shield_discovery_operation
  name: example-api-shield-discovery-operation
spec:
  forProvider:
    operationId: f174e90a-fafe-4643-bbbc-4a0ed4fc8415
    state: review
    zoneIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
